"""Generate dense *size/config variants* for model families we've already validated.

The architecturally-distinct models (gpt2_xl, llama3_8b, olmo2_7b, qwen3_0_6b, gemma3_27b, smollm3_3b,
plus the MoE/MLA/hybrid references) are hand-written. The remaining dense models in those families
differ ONLY in config + metadata, so we stamp them out from the validated base files instead of
hand-copying ~180 lines each. The OUTPUT is a fully self-contained file per model (the repo's
nanoGPT-style invariant holds); this script is just how those files are produced.

Re-run any time (idempotent): `uv run python scripts/_gen_dense.py`.

Families and their validated base bodies:
  * llama  (RoPE + GQA + SwiGLU + RMSNorm)                 <- llama3_2_1b.py
  * qwen   (llama + per-head QK-Norm)                      <- qwen3_0_6b.py
  * gemma  (sliding/global + sandwich norm + GeGLU + ...)  <- gemma3_27b.py
"""

from __future__ import annotations

from pathlib import Path

MODELS = Path(__file__).resolve().parents[1] / "llm_gallery" / "models"


def body_of(stem: str) -> str:
    """Everything after the ``DEFAULT_PRESET = ...`` line: the shared architecture + __main__."""
    text = (MODELS / f"{stem}.py").read_text()
    i = text.index("\nDEFAULT_PRESET = ")
    j = text.index("\n", i + 1)  # end of the DEFAULT_PRESET line
    return text[j + 1 :].lstrip("\n")


BODIES = {
    "llama": body_of("llama3_2_1b"),
    "qwen": body_of("qwen3_0_6b"),
    "gemma": body_of("gemma3_27b"),
    "moe": body_of("qwen3_30b_a3b"),
    "gptoss": body_of("gpt_oss_20b"),
    "mla": body_of("deepseek_v3"),
    "mamba": body_of("nemotron3_nano_30b"),
    "deltanet": body_of("qwen3_next_80b_a3b"),
    "linear": body_of("kimi_linear"),
    "olmo": body_of("olmo2_7b"),
}
BASES = {
    "llama": "llama3_2_1b.py",
    "qwen": "qwen3_0_6b.py",
    "gemma": "gemma3_27b.py",
    "moe": "qwen3_30b_a3b.py",
    "gptoss": "gpt_oss_20b.py",
    "mla": "deepseek_v3.py",
    "mamba": "nemotron3_nano_30b.py",
    "deltanet": "qwen3_next_80b_a3b.py",
    "linear": "kimi_linear.py",
    "olmo": "olmo2_7b.py",
}

_PREAMBLE = '''"""{name}

{desc}

Architecture : {family_desc}
Reference    : {ref}  ← read this first; all building blocks are annotated there

Diagram: https://sebastianraschka.com/llm-architecture-gallery ({name})
Tech report: {tech}

Self-contained: every module below is defined in THIS file. Generated by scripts/_gen_dense.py from
the validated {base} base — edit that base (or this generator) rather than hand-editing here.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F

MODEL_NAME = "{name}"
RELEASE_DATE = "{release}"
GALLERY_URL = "https://sebastianraschka.com/llm-architecture-gallery"
TECH_REPORT_URL = "{tech}"


'''

CONFIG_LLAMA = """@dataclass
class Config:
    vocab_size: int = {vocab}
    context_length: int = {ctx}
    n_layer: int = {n_layer}
    n_head: int = {n_head}
    n_kv_head: int = {n_kv}
    n_embd: int = {n_embd}
    head_dim: int = {head_dim}
    intermediate_size: int = {inter}
    rope_theta: float = {theta}
    norm_eps: float = {eps}
    tie_embeddings: bool = {tie}


PRESETS: dict[str, Config] = {{
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=4, n_head=4, n_kv_head=2,
        n_embd=128, head_dim=32, intermediate_size=256, rope_theta=10000.0,
    ),
    "{slug}": Config(),
}}
DEFAULT_PRESET = "{slug}"


"""

CONFIG_GEMMA = """@dataclass
class Config:
    vocab_size: int = {vocab}
    context_length: int = {ctx}
    n_layer: int = {n_layer}
    n_head: int = {n_head}
    n_kv_head: int = {n_kv}
    n_embd: int = {n_embd}
    head_dim: int = {head_dim}
    intermediate_size: int = {inter}
    sliding_window: int = {window}
    global_every: int = {global_every}
    rope_theta_global: float = {theta_g}
    rope_theta_local: float = {theta_l}
    query_pre_attn_scalar: int = {qpa}
    norm_eps: float = {eps}


PRESETS: dict[str, Config] = {{
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=6, n_head=4, n_kv_head={tiny_kv},
        n_embd=128, head_dim=32, intermediate_size=256, sliding_window=16, global_every=3,
        rope_theta_global=10000.0, rope_theta_local=10000.0, query_pre_attn_scalar=32,
    ),
    "{slug}": Config(),
}}
DEFAULT_PRESET = "{slug}"


"""

CONFIG_MOE = """@dataclass
class Config:
    vocab_size: int = {vocab}
    context_length: int = {ctx}
    n_layer: int = {n_layer}
    n_head: int = {n_head}
    n_kv_head: int = {n_kv}
    n_embd: int = {n_embd}
    head_dim: int = {head_dim}
    n_experts: int = {n_experts}
    n_experts_per_tok: int = {top_k}
    moe_intermediate_size: int = {moe_inter}
    intermediate_size: int = {inter}
    n_shared_experts: int = {n_shared}
    norm_topk_prob: bool = True
    moe_every: int = {moe_every}
    qk_norm: bool = {qk_norm}
    rope_theta: float = {theta}
    nope_every: int = {nope_every}
    sliding_window: int = {window}
    global_every: int = {global_every}
    global_first: bool = {global_first}
    attention_gate: bool = {attention_gate}
    norm_eps: float = {eps}
    tie_embeddings: bool = {tie}


PRESETS: dict[str, Config] = {{
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=4, n_head=4, n_kv_head=2, n_embd=128,
        head_dim=32, n_experts=8, n_experts_per_tok=2, moe_intermediate_size=128,
        intermediate_size=256, n_shared_experts={tiny_shared}, moe_every={moe_every},
        qk_norm={qk_norm}, rope_theta=10000.0, nope_every={nope_every}, sliding_window={tiny_window},
        global_every={global_every}, global_first={global_first}, attention_gate={attention_gate},
        tie_embeddings={tie},
    ),
    "{slug}": Config(),
}}
DEFAULT_PRESET = "{slug}"


"""

CONFIG_GPTOSS = """@dataclass
class Config:
    vocab_size: int = {vocab}
    context_length: int = {ctx}
    n_layer: int = {n_layer}
    n_head: int = {n_head}
    n_kv_head: int = {n_kv}
    n_embd: int = {n_embd}
    head_dim: int = {head_dim}
    n_experts: int = {n_experts}
    n_experts_per_tok: int = {top_k}
    moe_intermediate_size: int = {moe_inter}
    sliding_window: int = {window}
    rope_theta: float = {theta}
    norm_eps: float = {eps}
    tie_embeddings: bool = False


PRESETS: dict[str, Config] = {{
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=4, n_head=4, n_kv_head=2, n_embd=128,
        head_dim=32, n_experts=8, n_experts_per_tok=2, moe_intermediate_size=128,
        sliding_window=16, rope_theta=10000.0,
    ),
    "{slug}": Config(),
}}
DEFAULT_PRESET = "{slug}"


"""

CONFIG_MLA = """@dataclass
class Config:
    vocab_size: int = {vocab}
    context_length: int = {ctx}
    n_layer: int = {n_layer}
    n_embd: int = {n_embd}
    n_head: int = {n_head}
    q_lora_rank: int = {q_lora}
    kv_lora_rank: int = {kv_lora}
    qk_nope_head_dim: int = {qk_nope}
    qk_rope_head_dim: int = {qk_rope}
    v_head_dim: int = {v_head}
    n_experts: int = {n_experts}
    n_experts_per_tok: int = {top_k}
    n_shared_experts: int = {n_shared}
    moe_intermediate_size: int = {moe_inter}
    dense_intermediate_size: int = {dense_inter}
    first_k_dense: int = {first_k_dense}
    routed_scaling_factor: float = {scaling}
    rope_theta: float = {theta}
    norm_eps: float = {eps}
    tie_embeddings: bool = {tie}


PRESETS: dict[str, Config] = {{
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=4, n_embd=128, n_head=4,
        q_lora_rank=64, kv_lora_rank=32, qk_nope_head_dim=16, qk_rope_head_dim=16, v_head_dim=16,
        n_experts=8, n_experts_per_tok=2, n_shared_experts=1, moe_intermediate_size=128,
        dense_intermediate_size=256, first_k_dense=1, routed_scaling_factor=1.0, rope_theta=10000.0,
    ),
    "{slug}": Config(),
}}
DEFAULT_PRESET = "{slug}"


"""

CONFIG_MAMBA = """@dataclass
class Config:
    vocab_size: int = {vocab}
    context_length: int = {ctx}
    n_layer: int = {n_layer}
    n_embd: int = {n_embd}
    n_head: int = {n_head}
    n_kv_head: int = {n_kv}
    head_dim: int = {head_dim}
    rope_theta: float = {theta}
    layer_pattern: str = "{layer_pattern}"
    mamba_expand: int = {mamba_expand}
    mamba_d_state: int = {d_state}
    mamba_d_conv: int = {d_conv}
    mamba_dt_rank: int = {dt_rank}
    use_moe: bool = {use_moe}
    n_experts: int = {n_experts}
    n_experts_per_tok: int = {top_k}
    moe_intermediate_size: int = {moe_inter}
    n_shared_experts: int = {n_shared}
    intermediate_size: int = {inter}
    norm_eps: float = {eps}
    tie_embeddings: bool = {tie}


PRESETS: dict[str, Config] = {{
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=6, n_embd=128, n_head=4, n_kv_head=2,
        head_dim=32, rope_theta=10000.0, layer_pattern="ME*MEM", mamba_expand=2,
        mamba_d_state=8, mamba_d_conv=4, mamba_dt_rank=16, use_moe={use_moe}, n_experts=8,
        n_experts_per_tok=2, moe_intermediate_size=128, n_shared_experts=1, intermediate_size=256,
    ),
    "{slug}": Config(),
}}
DEFAULT_PRESET = "{slug}"


"""

CONFIG_DELTANET = """@dataclass
class Config:
    vocab_size: int = {vocab}
    context_length: int = {ctx}
    n_layer: int = {n_layer}
    n_embd: int = {n_embd}
    linear_n_head: int = {linear_n_head}
    n_head: int = {n_head}
    n_kv_head: int = {n_kv}
    head_dim: int = {head_dim}
    rope_theta: float = {theta}
    partial_rotary_factor: float = {partial_rotary_factor}
    attn_every: int = {attn_every}
    linear_conv_kernel_dim: int = {linear_conv_kernel_dim}
    n_experts: int = {n_experts}
    n_experts_per_tok: int = {top_k}
    moe_intermediate_size: int = {moe_inter}
    n_shared_experts: int = {n_shared}
    norm_eps: float = {eps}
    tie_embeddings: bool = {tie}


PRESETS: dict[str, Config] = {{
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=6, n_embd=128, linear_n_head=4, n_head=4,
        n_kv_head=2, head_dim=32, rope_theta=10000.0, partial_rotary_factor={partial_rotary_factor},
        attn_every=3, linear_conv_kernel_dim={linear_conv_kernel_dim}, n_experts=8,
        n_experts_per_tok=2, moe_intermediate_size=128, n_shared_experts=1,
    ),
    "{slug}": Config(),
}}
DEFAULT_PRESET = "{slug}"


"""

CONFIG_HYBRID = """@dataclass
class Config:
    vocab_size: int = {vocab}
    context_length: int = {ctx}
    n_layer: int = {n_layer}
    n_embd: int = {n_embd}
    linear_n_head: int = {linear_n_head}
    n_head: int = {n_head}
    n_kv_head: int = {n_kv}
    head_dim: int = {head_dim}
    rope_theta: float = {theta}
    attn_every: int = {attn_every}
    n_experts: int = {n_experts}
    n_experts_per_tok: int = {top_k}
    moe_intermediate_size: int = {moe_inter}
    n_shared_experts: int = {n_shared}
    norm_eps: float = {eps}
    tie_embeddings: bool = {tie}


PRESETS: dict[str, Config] = {{
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=6, n_embd=128, linear_n_head=4, n_head=4,
        n_kv_head=2, head_dim=32, rope_theta=10000.0, attn_every=3, n_experts=8,
        n_experts_per_tok=2, moe_intermediate_size=128, n_shared_experts=1,
    ),
    "{slug}": Config(),
}}
DEFAULT_PRESET = "{slug}"


"""

CONFIG_OLMO = """@dataclass
class Config:
    vocab_size: int = {vocab}
    context_length: int = {ctx}
    n_layer: int = {n_layer}
    n_head: int = {n_head}
    n_kv_head: int = {n_kv}
    n_embd: int = {n_embd}
    intermediate_size: int = {inter}
    rope_theta: float = {theta}
    sliding_window: int = {window}
    global_every: int = {global_every}
    norm_eps: float = {eps}


PRESETS: dict[str, Config] = {{
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=4, n_head=4, n_kv_head={tiny_kv},
        n_embd=128, intermediate_size=256, rope_theta=10000.0, sliding_window={tiny_window},
        global_every={global_every},
    ),
    "{slug}": Config(),
}}
DEFAULT_PRESET = "{slug}"


"""

CONFIG_TEMPLATES = {
    "llama": CONFIG_LLAMA,
    "qwen": CONFIG_LLAMA,
    "gemma": CONFIG_GEMMA,
    "moe": CONFIG_MOE,
    "gptoss": CONFIG_GPTOSS,
    "mla": CONFIG_MLA,
    "mamba": CONFIG_MAMBA,
    "deltanet": CONFIG_DELTANET,
    "linear": CONFIG_HYBRID,
    "olmo": CONFIG_OLMO,
}

FAMILY_DESC = {
    "llama": "RoPE · GQA · SwiGLU · RMSNorm (pre-norm dense)",
    "qwen": "RoPE · GQA · per-head QK-Norm · SwiGLU · RMSNorm",
    "gemma": "sliding-window + global attn · sandwich norm · QK-Norm · GeGLU",
    "moe": "GQA · top-k sparse MoE · RoPE · SwiGLU · RMSNorm",
    "gptoss": "MoE · attention sinks · alternating local/global attention",
    "mla": "Multi-head Latent Attention (MLA) · fine-grained MoE · shared experts",
    "mamba": "Mamba-2 SSM · periodic GQA hybrid · sparse MoE · RMSNorm",
    "deltanet": "Gated DeltaNet (linear attn) · gated GQA hybrid · sparse MoE",
    "linear": "Lightning linear attention · GQA hybrid · sparse MoE",
    "olmo": "GQA · QK-Norm · post-norm placement · RoPE",
}

FAMILY_REF = {
    "llama": "llama3_8b.py",
    "qwen": "qwen3_0_6b.py",
    "gemma": "gemma3_27b.py",
    "moe": "qwen3_30b_a3b.py",
    "gptoss": "gpt_oss_20b.py",
    "mla": "deepseek_v3.py",
    "mamba": "nemotron3_nano_30b.py",
    "deltanet": "qwen3_next_80b_a3b.py",
    "linear": "kimi_linear.py",
    "olmo": "olmo2_7b.py",
}

SPECS = [
    dict(
        module="llama3_2_3b",
        slug="llama3.2-3b",
        name="Llama 3.2 (3B)",
        release="2024-09-25",
        tech="https://arxiv.org/pdf/2407.21783",
        family="llama",
        vocab=128256,
        ctx=131072,
        n_layer=28,
        n_head=24,
        n_kv=8,
        n_embd=3072,
        head_dim=128,
        inter=8192,
        theta="500000.0",
        eps="1e-5",
        tie="True",
        desc="A 3B dense Llama-family model: RoPE + GQA + SwiGLU + RMSNorm with tied embeddings.\nSame architecture as llama3_8b.py — see it for the annotated walkthrough.",
    ),
    dict(
        module="mistral_small_3_1",
        slug="mistral-small-3.1",
        name="Mistral Small 3.1 (24B)",
        release="2025-03-18",
        tech="https://mistral.ai/news/mistral-small-3-1",
        family="llama",
        vocab=131072,
        ctx=131072,
        n_layer=40,
        n_head=32,
        n_kv=8,
        n_embd=5120,
        head_dim=128,
        inter=32768,
        theta="1000000000.0",
        eps="1e-5",
        tie="False",
        desc="Mistral Small 3.1: a dense GQA transformer (RoPE + SwiGLU + RMSNorm) with a decoupled\nhead_dim (128, vs n_embd/n_head=160). Architecturally Llama-style; see llama3_8b.py.",
    ),
    dict(
        module="phi_4",
        slug="phi-4",
        name="Phi-4 (14B)",
        release="2024-12-12",
        tech="https://arxiv.org/pdf/2412.08905",
        family="llama",
        vocab=100352,
        ctx=16384,
        n_layer=40,
        n_head=40,
        n_kv=10,
        n_embd=5120,
        head_dim=128,
        inter=17920,
        theta="250000.0",
        eps="1e-5",
        tie="True",
        desc="Phi-4: dense GQA + RoPE in the Llama style (pre-norm RMSNorm, SwiGLU), tied embeddings.\nNotable for its data-centric training recipe rather than architectural novelty.",
    ),
    dict(
        module="qwen3_4b",
        slug="qwen3-4b",
        name="Qwen3 (4B)",
        release="2025-04-28",
        tech="https://arxiv.org/pdf/2505.09388",
        family="qwen",
        vocab=151936,
        ctx=40960,
        n_layer=36,
        n_head=32,
        n_kv=8,
        n_embd=2560,
        head_dim=128,
        inter=9728,
        theta="1000000.0",
        eps="1e-6",
        tie="True",
        desc="Qwen3 4B: dense GQA + per-head QK-Norm + RoPE + SwiGLU, decoupled head_dim, tied\nembeddings. Same architecture as qwen3_0_6b.py, just larger.",
    ),
    dict(
        module="qwen3_8b",
        slug="qwen3-8b",
        name="Qwen3 (8B)",
        release="2025-04-28",
        tech="https://arxiv.org/pdf/2505.09388",
        family="qwen",
        vocab=151936,
        ctx=40960,
        n_layer=36,
        n_head=32,
        n_kv=8,
        n_embd=4096,
        head_dim=128,
        inter=12288,
        theta="1000000.0",
        eps="1e-6",
        tie="False",
        desc="Qwen3 8B: dense GQA + per-head QK-Norm + RoPE + SwiGLU. Larger Qwen3 models (8B+) do\nNOT tie embeddings. See qwen3_0_6b.py for the annotated blocks.",
    ),
    dict(
        module="qwen3_32b",
        slug="qwen3-32b",
        name="Qwen3 (32B)",
        release="2025-04-28",
        tech="https://arxiv.org/pdf/2505.09388",
        family="qwen",
        vocab=151936,
        ctx=40960,
        n_layer=64,
        n_head=64,
        n_kv=8,
        n_embd=5120,
        head_dim=128,
        inter=25600,
        theta="1000000.0",
        eps="1e-6",
        tie="False",
        desc="Qwen3 32B: the largest dense Qwen3. GQA + per-head QK-Norm + RoPE + SwiGLU, untied\nembeddings. Same architecture as qwen3_0_6b.py.",
    ),
    dict(
        module="gemma3_270m",
        slug="gemma3-270m",
        name="Gemma 3 (270M)",
        release="2025-08-14",
        tech="https://arxiv.org/pdf/2503.19786",
        family="gemma",
        vocab=262144,
        ctx=32768,
        n_layer=18,
        n_head=4,
        n_kv=1,
        n_embd=640,
        head_dim=256,
        inter=2048,
        window=512,
        global_every=6,
        theta_g="1000000.0",
        theta_l="10000.0",
        qpa=256,
        eps="1e-6",
        tiny_kv=1,
        desc="Gemma 3 270M: the smallest Gemma 3. Uses multi-query attention (MQA: a single shared K/V\nhead, n_kv_head=1) with the Gemma sliding/global + sandwich-norm recipe. See gemma3_27b.py.",
    ),
    # ---- MoE family (base: qwen3_30b_a3b) ----
    dict(
        module="qwen3_235b_a22b",
        slug="qwen3-235b-a22b",
        name="Qwen3 (235B-A22B)",
        release="2025-04-28",
        tech="https://arxiv.org/pdf/2505.09388",
        family="moe",
        vocab=151936,
        ctx=40960,
        n_layer=94,
        n_head=64,
        n_kv=4,
        n_embd=4096,
        head_dim=128,
        n_experts=128,
        top_k=8,
        moe_inter=1536,
        n_shared=0,
        qk_norm="True",
        theta="1000000.0",
        eps="1e-6",
        tie="False",
        tiny_shared=0,
        desc="Qwen3 235B-A22B: the large Qwen3 MoE. GQA + per-head QK-Norm + top-8 routing.\nSame MoE architecture as qwen3_30b_a3b.py, scaled up.",
    ),
    dict(
        module="qwen3_coder_flash",
        slug="qwen3-coder-flash",
        name="Qwen3 Coder Flash (30B-A3B)",
        release="2025-07-31",
        tech="https://arxiv.org/pdf/2505.09388",
        family="moe",
        vocab=151936,
        ctx=40960,
        n_layer=48,
        n_head=32,
        n_kv=4,
        n_embd=2048,
        head_dim=128,
        n_experts=128,
        top_k=8,
        moe_inter=768,
        n_shared=0,
        qk_norm="True",
        theta="1000000.0",
        eps="1e-6",
        tie="False",
        tiny_shared=0,
        desc="Qwen3 Coder Flash: a 30B-A3B Qwen3 MoE tuned for code. Architecture matches\nqwen3_30b_a3b.py.",
    ),
    dict(
        module="glm_4_5",
        slug="glm-4.5",
        name="GLM-4.5 (355B)",
        release="2025-07-28",
        tech="https://arxiv.org/pdf/2508.06471",
        family="moe",
        vocab=151552,
        ctx=131072,
        n_layer=92,
        n_head=96,
        n_kv=8,
        n_embd=5120,
        head_dim=128,
        n_experts=160,
        top_k=8,
        moe_inter=1536,
        n_shared=1,
        qk_norm="True",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=1,
        desc="GLM-4.5: a large MoE with GQA + QK-Norm and ONE always-on shared expert\n(n_shared_experts=1) alongside the routed experts. Config approximate.",
    ),
    dict(
        module="glm_4_7",
        slug="glm-4.7",
        name="GLM-4.7 (355B)",
        release="2025-12-22",
        tech="https://arxiv.org/pdf/2508.06471",
        family="moe",
        vocab=151552,
        ctx=131072,
        n_layer=92,
        n_head=96,
        n_kv=8,
        n_embd=5120,
        head_dim=128,
        n_experts=160,
        top_k=8,
        moe_inter=1536,
        n_shared=1,
        qk_norm="True",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=1,
        desc="GLM-4.7: same architecture as GLM-4.5 (MoE + GQA + QK-Norm + 1 shared expert),\nlater training. Config approximate.",
    ),
    dict(
        module="glm_4_5_air",
        slug="glm-4.5-air",
        name="GLM-4.5-Air (106B)",
        release="2025-07-28",
        tech="https://arxiv.org/pdf/2508.06471",
        family="moe",
        vocab=151552,
        ctx=131072,
        n_layer=46,
        n_head=96,
        n_kv=8,
        n_embd=4096,
        head_dim=128,
        n_experts=128,
        top_k=8,
        moe_inter=1408,
        n_shared=1,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=1,
        desc="GLM-4.5-Air: the smaller GLM-4.5 MoE (no QK-Norm), with one shared expert.\nConfig approximate.",
    ),
    dict(
        module="grok_2_5",
        slug="grok-2.5",
        name="Grok 2.5 (270B)",
        release="2025-08-22",
        tech="https://sebastianraschka.com/llm-architecture-gallery",
        family="moe",
        vocab=131072,
        ctx=131072,
        n_layer=64,
        n_head=64,
        n_kv=8,
        n_embd=8192,
        head_dim=128,
        n_experts=8,
        top_k=2,
        moe_inter=16384,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="Grok 2.5: a coarse-grained MoE (few large experts, top-2) with GQA, no QK-Norm.\nConfig approximate (xAI has not published full details).",
    ),
    dict(
        module="minimax_m2",
        slug="minimax-m2",
        name="MiniMax M2 (230B)",
        release="2025-10-23",
        tech="https://arxiv.org/abs/2605.26494",
        family="moe",
        vocab=200064,
        ctx=131072,
        n_layer=62,
        n_head=48,
        n_kv=8,
        n_embd=6144,
        head_dim=128,
        n_experts=256,
        top_k=8,
        moe_inter=1536,
        n_shared=0,
        qk_norm="True",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="MiniMax M2: fine-grained MoE (many experts) with GQA + QK-Norm. Config approximate.",
    ),
    dict(
        module="minimax_m2_5",
        slug="minimax-m2.5",
        name="MiniMax-M2.5 (230B)",
        release="2026-02-12",
        tech="https://arxiv.org/abs/2605.26494",
        family="moe",
        vocab=200064,
        ctx=131072,
        n_layer=62,
        n_head=48,
        n_kv=8,
        n_embd=6144,
        head_dim=128,
        n_experts=256,
        top_k=8,
        moe_inter=1536,
        n_shared=0,
        qk_norm="True",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="MiniMax-M2.5: iteration on MiniMax M2 (MoE + GQA + QK-Norm). Config approximate.",
    ),
    dict(
        module="minimax_m2_7",
        slug="minimax-m2.7",
        name="MiniMax M2.7 (230B)",
        release="2026-03-18",
        tech="https://arxiv.org/abs/2605.26494",
        family="moe",
        vocab=200064,
        ctx=131072,
        n_layer=62,
        n_head=48,
        n_kv=8,
        n_embd=6144,
        head_dim=128,
        n_experts=256,
        top_k=8,
        moe_inter=1536,
        n_shared=0,
        qk_norm="True",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="MiniMax M2.7: iteration on MiniMax M2 (MoE + GQA + QK-Norm). Config approximate.",
    ),
    dict(
        module="intellect_3",
        slug="intellect-3",
        name="INTELLECT-3 (106B)",
        release="2025-11-26",
        tech="https://storage.googleapis.com/intellect-3-paper/INTELLECT_3_Technical_Report.pdf",
        family="moe",
        vocab=151552,
        ctx=131072,
        n_layer=46,
        n_head=96,
        n_kv=8,
        n_embd=4096,
        head_dim=128,
        n_experts=128,
        top_k=8,
        moe_inter=1408,
        n_shared=1,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=1,
        desc="INTELLECT-3: a GLM-4.5-Air-style MoE (GQA + 1 shared expert) RL-trained by Prime\nIntellect. Config approximate.",
    ),
    dict(
        module="sarvam_30b",
        slug="sarvam-30b",
        name="Sarvam (30B)",
        release="2026-03-03",
        tech="https://www.sarvam.ai/blogs/sarvam-30b-105b",
        family="moe",
        vocab=151936,
        ctx=40960,
        n_layer=48,
        n_head=32,
        n_kv=4,
        n_embd=2048,
        head_dim=128,
        n_experts=128,
        top_k=8,
        moe_inter=768,
        n_shared=0,
        qk_norm="True",
        theta="1000000.0",
        eps="1e-6",
        tie="False",
        tiny_shared=0,
        desc="Sarvam 30B: a Qwen3-MoE-style model (GQA + QK-Norm + top-8 routing). Config approximate.",
    ),
    # ---- gpt-oss family (base: gpt_oss_20b) ----
    dict(
        module="gpt_oss_120b",
        slug="gpt-oss-120b",
        name="GPT-OSS (120B)",
        release="2025-08-04",
        tech="https://cdn.openai.com/pdf/419b6906-9da6-406c-a19d-1bb078ac7637/oai_gpt-oss_model_card.pdf",
        family="gptoss",
        vocab=201088,
        ctx=131072,
        n_layer=36,
        n_head=64,
        n_kv=8,
        n_embd=2880,
        head_dim=64,
        n_experts=128,
        top_k=4,
        moe_inter=2880,
        window=128,
        theta="150000.0",
        eps="1e-5",
        desc="GPT-OSS 120B: the larger gpt-oss. MoE + alternating sliding/global attention +\nattention sinks. Same architecture as gpt_oss_20b.py, scaled up.",
    ),
    # ---- MLA family (base: deepseek_v3) ----
    dict(
        module="deepseek_r1",
        slug="deepseek-r1",
        name="DeepSeek R1 (671B)",
        release="2025-01-20",
        tech="https://arxiv.org/pdf/2501.12948",
        family="mla",
        vocab=129280,
        ctx=4096,
        n_layer=61,
        n_embd=7168,
        n_head=128,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=256,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=18432,
        first_k_dense=3,
        scaling="2.5",
        theta="10000.0",
        eps="1e-6",
        tie="False",
        desc="DeepSeek R1: architecturally identical to DeepSeek V3 (MLA + DeepSeekMoE), RL-tuned for\nreasoning. See deepseek_v3.py for the annotated MLA + MoE.",
    ),
    dict(
        module="deepseek_v3_2",
        slug="deepseek-v3.2",
        name="DeepSeek V3.2 (671B)",
        release="2025-12-01",
        tech="https://arxiv.org/pdf/2512.02556",
        family="mla",
        vocab=129280,
        ctx=4096,
        n_layer=61,
        n_embd=7168,
        n_head=128,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=256,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=18432,
        first_k_dense=3,
        scaling="2.5",
        theta="10000.0",
        eps="1e-6",
        tie="False",
        desc="DeepSeek V3.2: V3 plus a sparse-attention mechanism (DeepSeek Sparse Attention).\nASSUMPTION: sparse key-selection/index sharing is documented, but this educational body uses full MLA attention.",
    ),
    dict(
        module="deepseek_v4_flash",
        slug="deepseek-v4-flash",
        name="DeepSeek V4-Flash (284B)",
        release="2026-04-24",
        tech="https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash/blob/main/DeepSeek_V4.pdf",
        family="mla",
        vocab=129280,
        ctx=4096,
        n_layer=48,
        n_embd=5120,
        n_head=96,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=256,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=12288,
        first_k_dense=2,
        scaling="2.5",
        theta="10000.0",
        eps="1e-6",
        tie="False",
        desc="DeepSeek V4-Flash: MLA + MoE with compressed sparse attention. Config approximate.\nASSUMPTION: compressed-sparse key selection is documented, but full MLA attention is used.",
    ),
    dict(
        module="deepseek_v4_pro",
        slug="deepseek-v4-pro",
        name="DeepSeek V4-Pro (1.6T)",
        release="2026-04-24",
        tech="https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro/blob/main/DeepSeek_V4.pdf",
        family="mla",
        vocab=129280,
        ctx=4096,
        n_layer=61,
        n_embd=7168,
        n_head=128,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=384,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=18432,
        first_k_dense=3,
        scaling="2.5",
        theta="10000.0",
        eps="1e-6",
        tie="False",
        desc="DeepSeek V4-Pro: largest DeepSeek MoE with compressed sparse attention and mHC.\nConfig approximate. ASSUMPTION: sparse key selection and mHC are documented, but full MLA attention is used.",
    ),
    dict(
        module="kimi_k2",
        slug="kimi-k2",
        name="Kimi K2 (1T)",
        release="2025-07-10",
        tech="https://arxiv.org/pdf/2507.20534",
        family="mla",
        vocab=163840,
        ctx=4096,
        n_layer=61,
        n_embd=7168,
        n_head=64,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=384,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=18432,
        first_k_dense=1,
        scaling="2.5",
        theta="10000.0",
        eps="1e-6",
        tie="False",
        desc="Kimi K2: a 1T-parameter MLA + MoE model (more, finer experts than DeepSeek V3).\nSame MLA + MoE architecture as deepseek_v3.py. Config approximate.",
    ),
    dict(
        module="kimi_k2_5",
        slug="kimi-k2.5",
        name="Kimi K2.5 (1T)",
        release="2026-01-27",
        tech="https://arxiv.org/pdf/2602.02276",
        family="mla",
        vocab=163840,
        ctx=4096,
        n_layer=61,
        n_embd=7168,
        n_head=64,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=384,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=18432,
        first_k_dense=1,
        scaling="2.5",
        theta="10000.0",
        eps="1e-6",
        tie="False",
        desc="Kimi K2.5: iteration on Kimi K2 (MLA + MoE). Config approximate.",
    ),
    dict(
        module="kimi_k2_6",
        slug="kimi-k2.6",
        name="Kimi K2.6 (1T)",
        release="",
        tech="",
        family="mla",
        vocab=163840,
        ctx=4096,
        n_layer=61,
        n_embd=7168,
        n_head=64,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=384,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=18432,
        first_k_dense=1,
        scaling="2.5",
        theta="10000.0",
        eps="1e-6",
        tie="False",
        desc="Kimi K2.6: iteration on Kimi K2 (MLA + MoE). Config approximate.",
    ),
    dict(
        module="kimi_k2_7_code",
        slug="kimi-k2.7-code",
        name="Kimi K2.7 Code (1T)",
        release="2026-06-12",
        tech="https://huggingface.co/moonshotai/Kimi-K2.7-Code",
        family="mla",
        vocab=163840,
        ctx=262144,
        n_layer=61,
        n_embd=7168,
        n_head=64,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=384,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=18432,
        first_k_dense=1,
        scaling="2.827",
        theta="50000.0",
        eps="1e-5",
        tie="False",
        desc="Kimi K2.7 Code: coding-focused Kimi K2.5/K2.6 text stack. The public config uses\nDeepSeek-style MLA + fine-grained MoE with one shared expert and 256K context.",
    ),
    dict(
        module="mistral_large_3",
        slug="mistral-large-3",
        name="Mistral Large 3 (673B)",
        release="2025-12-02",
        tech="https://sebastianraschka.com/llm-architecture-gallery",
        family="mla",
        vocab=131072,
        ctx=4096,
        n_layer=61,
        n_embd=7168,
        n_head=96,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=256,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=16384,
        first_k_dense=3,
        scaling="2.5",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        desc="Mistral Large 3: a large MLA + MoE model. Config approximate; see deepseek_v3.py.",
    ),
    dict(
        module="glm_5",
        slug="glm-5",
        name="GLM-5 (744B)",
        release="2026-02-11",
        tech="https://arxiv.org/pdf/2602.15763",
        family="mla",
        vocab=151552,
        ctx=4096,
        n_layer=92,
        n_embd=5120,
        n_head=96,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=160,
        top_k=8,
        n_shared=1,
        moe_inter=1536,
        dense_inter=12288,
        first_k_dense=3,
        scaling="2.5",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        desc="GLM-5: GLM moves to MLA + MoE (+ sparse attention). Config approximate.\nASSUMPTION: sparse key selection / index sharing is documented, but full MLA attention is used.",
    ),
    dict(
        module="glm_5_1",
        slug="glm-5.1",
        name="GLM-5.1 (744B)",
        release="",
        tech="",
        family="mla",
        vocab=151552,
        ctx=4096,
        n_layer=92,
        n_embd=5120,
        n_head=96,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=160,
        top_k=8,
        n_shared=1,
        moe_inter=1536,
        dense_inter=12288,
        first_k_dense=3,
        scaling="2.5",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        desc="GLM-5.1: iteration on GLM-5 (MLA + MoE). Config approximate.\nASSUMPTION: sparse key selection / index sharing is documented, but full MLA attention is used.",
    ),
    dict(
        module="glm_5_2",
        slug="glm-5.2",
        name="GLM-5.2 (744B)",
        release="2026-06-17",
        tech="https://arxiv.org/pdf/2602.15763",
        family="mla",
        vocab=154880,
        ctx=1048576,
        n_layer=78,
        n_embd=6144,
        n_head=64,
        q_lora=2048,
        kv_lora=512,
        qk_nope=192,
        qk_rope=64,
        v_head=256,
        n_experts=256,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=12288,
        first_k_dense=3,
        scaling="2.5",
        theta="8000000.0",
        eps="1e-5",
        tie="False",
        desc="GLM-5.2: GLM-5-family MLA + MoE with DeepSeek Sparse Attention and IndexShare.\nASSUMPTION: DSA index selection and IndexShare are documented in config/diagram, but full MLA is used.",
    ),
    dict(
        module="sarvam_105b",
        slug="sarvam-105b",
        name="Sarvam (105B)",
        release="2026-03-03",
        tech="https://www.sarvam.ai/blogs/sarvam-30b-105b",
        family="mla",
        vocab=151936,
        ctx=4096,
        n_layer=61,
        n_embd=6144,
        n_head=64,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=256,
        top_k=8,
        n_shared=1,
        moe_inter=2048,
        dense_inter=14336,
        first_k_dense=3,
        scaling="2.5",
        theta="1000000.0",
        eps="1e-6",
        tie="False",
        desc="Sarvam 105B: an MLA + MoE model. Config approximate; see deepseek_v3.py.",
    ),
    dict(
        module="longcat_flash_lite",
        slug="longcat-flash-lite",
        name="LongCat-Flash-Lite (68.5B-A3B)",
        release="2026-01-28",
        tech="https://arxiv.org/abs/2601.21204",
        family="mla",
        vocab=131072,
        ctx=4096,
        n_layer=40,
        n_embd=4096,
        n_head=64,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=256,
        top_k=8,
        n_shared=1,
        moe_inter=1024,
        dense_inter=8192,
        first_k_dense=1,
        scaling="2.5",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        desc="LongCat-Flash-Lite: an MLA + MoE model. Config approximate.",
    ),
    dict(
        module="mistral_small_4",
        slug="mistral-small-4",
        name="Mistral Small 4 (119B)",
        release="2026-03-16",
        tech="https://mistral.ai/news/mistral-small-4",
        family="mla",
        vocab=131072,
        ctx=4096,
        n_layer=48,
        n_embd=5120,
        n_head=64,
        q_lora=1536,
        kv_lora=512,
        qk_nope=128,
        qk_rope=64,
        v_head=128,
        n_experts=128,
        top_k=8,
        n_shared=1,
        moe_inter=1536,
        dense_inter=12288,
        first_k_dense=2,
        scaling="2.5",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        desc="Mistral Small 4: a smaller MLA + MoE Mistral. Config approximate.",
    ),
    # ---- Mamba-2 hybrid family (base: nemotron3_nano_30b) ----
    dict(
        module="nemotron3_super_120b",
        slug="nemotron3-super-120b",
        name="Nemotron 3 Super (120B-A12B)",
        release="2026-03-11",
        tech="https://research.nvidia.com/labs/nemotron/files/NVIDIA-Nemotron-3-Super-Technical-Report.pdf",
        family="mamba",
        vocab=131072,
        ctx=8192,
        n_layer=56,
        n_embd=6144,
        n_head=48,
        n_kv=8,
        head_dim=128,
        theta="1000000.0",
        attn_every=6,
        mamba_expand=2,
        d_state=128,
        d_conv=4,
        dt_rank=96,
        use_moe="True",
        n_experts=128,
        top_k=8,
        moe_inter=1536,
        n_shared=1,
        inter=18432,
        eps="1e-5",
        tie="False",
        desc="Nemotron 3 Super: larger Mamba-2 hybrid with (latent) MoE. Config approximate.\nASSUMPTION: latent-MoE compression simplified to standard MoE. See nemotron3_nano_30b.py.",
    ),
    dict(
        module="nemotron3_ultra",
        slug="nemotron3-ultra",
        name="Nemotron 3 Ultra (550B-A55B)",
        release="",
        tech="https://research.nvidia.com/labs/nemotron/files/NVIDIA-Nemotron-3-Ultra-Technical-Report.pdf",
        family="mamba",
        vocab=131072,
        ctx=8192,
        n_layer=80,
        n_embd=8192,
        n_head=64,
        n_kv=8,
        head_dim=128,
        theta="1000000.0",
        attn_every=6,
        mamba_expand=2,
        d_state=128,
        d_conv=4,
        dt_rank=128,
        use_moe="True",
        n_experts=256,
        top_k=8,
        moe_inter=2048,
        n_shared=1,
        inter=21504,
        eps="1e-5",
        tie="False",
        desc="Nemotron 3 Ultra: the largest Nemotron — sparse hybrid Mamba + MoE. Config approximate.",
    ),
    dict(
        module="nemotron3_nano_4b",
        slug="nemotron3-nano-4b",
        name="Nemotron 3 Nano (4B)",
        release="2026-03-16",
        tech="https://huggingface.co/blog/nvidia/nemotron-3-nano-4b",
        family="mamba",
        vocab=131072,
        ctx=8192,
        n_layer=32,
        n_embd=2560,
        n_head=20,
        n_kv=4,
        head_dim=128,
        theta="1000000.0",
        attn_every=6,
        mamba_expand=2,
        d_state=64,
        d_conv=4,
        dt_rank=80,
        use_moe="False",
        n_experts=8,
        top_k=2,
        moe_inter=128,
        n_shared=1,
        inter=9728,
        eps="1e-5",
        tie="True",
        desc="Nemotron 3 Nano 4B: a DENSE hybrid (Mamba-2 + GQA, no MoE — use_moe=False).\nSee nemotron3_nano_30b.py for the Mamba block.",
    ),
    # ---- Gated DeltaNet family (base: qwen3_next_80b_a3b) ----
    dict(
        module="qwen3_5",
        slug="qwen3.5",
        name="Qwen3.5 (397B)",
        release="2026-02-16",
        tech="",
        family="deltanet",
        vocab=151936,
        ctx=40960,
        n_layer=62,
        n_embd=4096,
        linear_n_head=32,
        n_head=32,
        n_kv=4,
        head_dim=128,
        theta="1000000.0",
        attn_every=4,
        n_experts=512,
        top_k=10,
        moe_inter=512,
        n_shared=1,
        eps="1e-6",
        tie="False",
        desc="Qwen3.5: larger Gated DeltaNet + gated-attention hybrid with MoE. Config approximate.\nSee qwen3_next_80b_a3b.py.",
    ),
    dict(
        module="qwen3_6_35b_a3b",
        slug="qwen3.6-35b-a3b",
        name="Qwen3.6 (35B-A3B)",
        release="",
        tech="",
        family="deltanet",
        vocab=151936,
        ctx=40960,
        n_layer=48,
        n_embd=2048,
        linear_n_head=16,
        n_head=16,
        n_kv=2,
        head_dim=128,
        theta="1000000.0",
        attn_every=4,
        n_experts=128,
        top_k=8,
        moe_inter=512,
        n_shared=1,
        eps="1e-6",
        tie="False",
        desc="Qwen3.6 35B-A3B: sparse hybrid attention (Gated DeltaNet + gated attention) + MoE.\nConfig approximate.",
    ),
    # ---- Linear-attention family (base: kimi_linear) ----
    dict(
        module="ling_2_5",
        slug="ling-2.5",
        name="Ling 2.5 (1T)",
        release="2026-02-15",
        tech="",
        family="linear",
        vocab=126464,
        ctx=40960,
        n_layer=61,
        n_embd=4096,
        linear_n_head=32,
        n_head=32,
        n_kv=4,
        head_dim=128,
        theta="1000000.0",
        attn_every=4,
        n_experts=256,
        top_k=8,
        moe_inter=1024,
        n_shared=1,
        eps="1e-5",
        tie="False",
        desc="Ling 2.5: a 1T Lightning-attention + full-attention hybrid with MoE. Config approximate.\nASSUMPTION: full-attention layers use GQA here, not MLA. See kimi_linear.py.",
    ),
    dict(
        module="ling_2_6",
        slug="ling-2.6",
        name="Ling 2.6 (1T)",
        release="",
        tech="",
        family="linear",
        vocab=126464,
        ctx=40960,
        n_layer=61,
        n_embd=4096,
        linear_n_head=32,
        n_head=32,
        n_kv=4,
        head_dim=128,
        theta="1000000.0",
        attn_every=4,
        n_experts=256,
        top_k=8,
        moe_inter=1024,
        n_shared=1,
        eps="1e-5",
        tie="False",
        desc="Ling 2.6: iteration on Ling 2.5 (linear-attention hybrid + MoE). Config approximate.\nASSUMPTION: full-attention layers use GQA here, not MLA. See kimi_linear.py.",
    ),
    # ---- OLMo 3 (base: olmo2_7b — QK-Norm + post-norm) ----
    dict(
        module="olmo3_7b",
        slug="olmo3-7b",
        name="OLMo 3 (7B)",
        release="2025-11-20",
        tech="https://arxiv.org/pdf/2512.13961",
        family="olmo",
        vocab=100352,
        ctx=4096,
        n_layer=32,
        n_head=32,
        n_kv=32,
        n_embd=4096,
        inter=11008,
        theta="500000.0",
        eps="1e-6",
        tiny_kv=4,
        desc="OLMo 3 7B: OLMo 2's recipe (full-dim QK-Norm + post-norm), full MHA,\nwith the published 3 sliding-window / 1 full-attention schedule.",
    ),
    dict(
        module="olmo3_32b",
        slug="olmo3-32b",
        name="OLMo 3 (32B)",
        release="2025-11-20",
        tech="https://arxiv.org/pdf/2512.13961",
        family="olmo",
        vocab=100352,
        ctx=4096,
        n_layer=64,
        n_head=40,
        n_kv=8,
        n_embd=5120,
        inter=13824,
        theta="500000.0",
        eps="1e-6",
        tiny_kv=2,
        desc="OLMo 3 32B: OLMo 2's recipe (QK-Norm + post-norm) with GQA,\nwith the published 3 sliding-window / 1 full-attention schedule.",
    ),
    # ---- dense long-tail (base: llama3_2_1b / qwen3_0_6b) ----
    dict(
        module="nanbeige_4_1",
        slug="nanbeige-4.1",
        name="Nanbeige 4.1 (3B)",
        release="2026-02-10",
        tech="https://arxiv.org/pdf/2602.13367",
        family="llama",
        vocab=128256,
        ctx=32768,
        n_layer=28,
        n_head=24,
        n_kv=8,
        n_embd=3072,
        head_dim=128,
        inter=8192,
        theta="1000000.0",
        eps="1e-5",
        tie="True",
        desc="Nanbeige 4.1: a dense GQA transformer. Config approximate.",
    ),
    dict(
        module="granite_4_1",
        slug="granite-4.1",
        name="Granite 4.1 (30B)",
        release="",
        tech="",
        family="llama",
        vocab=49152,
        ctx=131072,
        n_layer=40,
        n_head=32,
        n_kv=8,
        n_embd=4096,
        head_dim=128,
        inter=12800,
        theta="1000000.0",
        eps="1e-5",
        tie="True",
        desc="Granite 4.1 (30B): modeled as a dense GQA transformer per the gallery's 'dense attention'.\nNOTE: Granite 4 is in reality a Mamba/transformer hybrid; this is a dense approximation.",
    ),
    dict(
        module="lfm2_5_1_2b",
        slug="lfm2.5-1.2b",
        name="LFM2.5 (1.2B)",
        release="",
        tech="",
        family="llama",
        vocab=65536,
        ctx=32768,
        n_layer=16,
        n_head=16,
        n_kv=8,
        n_embd=2048,
        head_dim=128,
        inter=8192,
        theta="1000000.0",
        eps="1e-5",
        tie="True",
        desc="LFM2.5 1.2B: modeled as a dense GQA transformer.\nNOTE: Liquid LFM2 actually uses short-conv + attention; this is a dense approximation.",
    ),
    dict(
        module="lfm2_5_350m",
        slug="lfm2.5-350m",
        name="LFM2.5 (350M)",
        release="",
        tech="",
        family="llama",
        vocab=65536,
        ctx=32768,
        n_layer=12,
        n_head=8,
        n_kv=4,
        n_embd=1024,
        head_dim=128,
        inter=4096,
        theta="1000000.0",
        eps="1e-5",
        tie="True",
        desc="LFM2.5 350M: modeled as a dense GQA transformer.\nNOTE: Liquid LFM2 actually uses short-conv + attention; this is a dense approximation.",
    ),
    dict(
        module="qwen3_6_27b",
        slug="qwen3.6-27b",
        name="Qwen3.6 (27B)",
        release="",
        tech="",
        family="qwen",
        vocab=151936,
        ctx=40960,
        n_layer=64,
        n_head=40,
        n_kv=8,
        n_embd=5120,
        head_dim=128,
        inter=25600,
        theta="1000000.0",
        eps="1e-6",
        tie="False",
        desc="Qwen3.6 27B: dense GQA + per-head QK-Norm (same as qwen3_0_6b.py). Config approximate.",
    ),
    dict(
        module="vibethinker_3b",
        slug="vibethinker-3b",
        name="VibeThinker-3B (3B)",
        release="2026-06-15",
        tech="https://arxiv.org/abs/2606.16140",
        family="llama",
        vocab=151936,
        ctx=131072,
        n_layer=36,
        n_head=16,
        n_kv=2,
        n_embd=2048,
        head_dim=128,
        inter=11008,
        theta="1000000.0",
        eps="1e-6",
        tie="True",
        desc="VibeThinker-3B: Qwen2.5-Coder-style dense GQA + RoPE + SwiGLU + RMSNorm stack.\nThe reasoning gains come from post-training; no QK-Norm is present in the public config.",
    ),
    # ---- Gemma 4 (base: gemma3_27b) ----
    dict(
        module="gemma4_31b",
        slug="gemma4-31b",
        name="Gemma 4 (31B)",
        release="2026-04-02",
        tech="https://ai.google.dev/gemma/docs/core/model_card_4",
        family="gemma",
        vocab=262144,
        ctx=131072,
        n_layer=62,
        n_head=32,
        n_kv=16,
        n_embd=5376,
        head_dim=128,
        inter=21504,
        window=1024,
        global_every=6,
        theta_g="1000000.0",
        theta_l="10000.0",
        qpa=168,
        eps="1e-6",
        tiny_kv=2,
        desc="Gemma 4 31B: same architecture family as Gemma 3 (GQA + QK-Norm +\nsliding/global + sandwich norm). Config approximate. See gemma3_27b.py.",
    ),
    dict(
        module="gemma4_12b",
        slug="gemma4-12b",
        name="Gemma 4 (12B)",
        release="2026-06-03",
        tech="https://developers.googleblog.com/gemma-4-12b-the-developer-guide/",
        family="gemma",
        vocab=262144,
        ctx=131072,
        n_layer=48,
        n_head=16,
        n_kv=8,
        n_embd=3840,
        head_dim=256,
        inter=15360,
        window=1024,
        global_every=6,
        theta_g="1000000.0",
        theta_l="10000.0",
        qpa=256,
        eps="1e-6",
        tiny_kv=2,
        desc="Gemma 4 12B: Gemma-3-style (sliding/global + sandwich norm).\nConfig approximate.",
    ),
    dict(
        module="gemma4_e4b",
        slug="gemma4-e4b",
        name="Gemma 4 (E4B)",
        release="2026-04-02",
        tech="https://ai.google.dev/gemma/docs/core/model_card_4",
        family="gemma",
        vocab=262144,
        ctx=131072,
        n_layer=35,
        n_head=16,
        n_kv=8,
        n_embd=2560,
        head_dim=256,
        inter=10240,
        window=1024,
        global_every=6,
        theta_g="1000000.0",
        theta_l="10000.0",
        qpa=256,
        eps="1e-6",
        tiny_kv=2,
        desc="Gemma 4 E4B: Gemma-3-style GQA + sliding/global. Config approximate.",
    ),
    dict(
        module="gemma4_e2b",
        slug="gemma4-e2b",
        name="Gemma 4 (E2B)",
        release="2026-04-02",
        tech="https://ai.google.dev/gemma/docs/core/model_card_4",
        family="gemma",
        vocab=262144,
        ctx=131072,
        n_layer=30,
        n_head=8,
        n_kv=1,
        n_embd=2048,
        head_dim=256,
        inter=8192,
        window=1024,
        global_every=6,
        theta_g="1000000.0",
        theta_l="10000.0",
        qpa=256,
        eps="1e-6",
        tiny_kv=1,
        desc="Gemma 4 E2B: smallest Gemma 4, multi-query attention (n_kv_head=1) +\nsliding/global. Config approximate.",
    ),
    # ---- MoE long-tail (base: qwen3_30b_a3b) ----
    dict(
        module="llama4_maverick",
        slug="llama4-maverick",
        name="Llama 4 Maverick (400B)",
        release="2025-04-05",
        tech="https://ai.meta.com/blog/llama-4-multimodal-intelligence/",
        family="moe",
        vocab=202048,
        ctx=131072,
        n_layer=48,
        n_head=40,
        n_kv=8,
        n_embd=5120,
        head_dim=128,
        n_experts=128,
        top_k=1,
        moe_inter=8192,
        n_shared=1,
        qk_norm="False",
        theta="500000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=1,
        desc="Llama 4 Maverick: MoE + GQA with a shared expert, top-1 routing, alternating MoE,\nand an interleaved NoPE/iRoPE-style schedule. Config approximate.",
    ),
    dict(
        module="arcee_trinity_large",
        slug="arcee-trinity-large",
        name="Arcee Trinity Large (400B)",
        release="2026-01-27",
        tech="https://arxiv.org/pdf/2602.17004",
        family="moe",
        vocab=128256,
        ctx=131072,
        n_layer=48,
        n_head=64,
        n_kv=8,
        n_embd=8192,
        head_dim=128,
        n_experts=128,
        top_k=8,
        moe_inter=2048,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="Arcee Trinity Large: MoE + gated attention. ASSUMPTION: exact sliding/global cadence is\nnot public in the fixture set; this uses gated GQA with full causal attention. Config approximate.",
    ),
    dict(
        module="step_3_5_flash",
        slug="step-3.5-flash",
        name="Step 3.5 Flash (196B)",
        release="2026-02-01",
        tech="https://arxiv.org/pdf/2602.10604",
        family="moe",
        vocab=128815,
        ctx=131072,
        n_layer=48,
        n_head=64,
        n_kv=8,
        n_embd=5120,
        head_dim=128,
        n_experts=128,
        top_k=8,
        moe_inter=1536,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="Step 3.5 Flash: MoE with gated attention and a 1 full / 3 sliding-window schedule.\nConfig approximate.",
    ),
    dict(
        module="mimo_v2_flash",
        slug="mimo-v2-flash",
        name="Xiaomi MiMo-V2-Flash (309B)",
        release="2025-12-16",
        tech="https://arxiv.org/pdf/2601.02780",
        family="moe",
        vocab=151552,
        ctx=131072,
        n_layer=48,
        n_head=64,
        n_kv=8,
        n_embd=5120,
        head_dim=128,
        n_experts=128,
        top_k=8,
        moe_inter=1536,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="Xiaomi MiMo-V2-Flash: MoE with sliding-window attention metadata.\nASSUMPTION: exact global cadence is not explicit in the public config; this uses sliding attention in every layer.",
    ),
    dict(
        module="mimo_v2_5",
        slug="mimo-v2.5",
        name="Xiaomi MiMo-V2.5 (310B)",
        release="",
        tech="",
        family="moe",
        vocab=151552,
        ctx=131072,
        n_layer=48,
        n_head=64,
        n_kv=8,
        n_embd=5120,
        head_dim=128,
        n_experts=128,
        top_k=8,
        moe_inter=1536,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="Xiaomi MiMo-V2.5: sparse MoE. Config approximate.",
    ),
    dict(
        module="mimo_v2_5_pro",
        slug="mimo-v2.5-pro",
        name="Xiaomi MiMo-V2.5-Pro (1.02T)",
        release="",
        tech="",
        family="moe",
        vocab=151552,
        ctx=131072,
        n_layer=61,
        n_head=96,
        n_kv=8,
        n_embd=7168,
        head_dim=128,
        n_experts=256,
        top_k=8,
        moe_inter=2048,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="Xiaomi MiMo-V2.5-Pro: large sparse MoE. Config approximate.",
    ),
    dict(
        module="hunyuan_3_preview",
        slug="hunyuan-3-preview",
        name="Tencent Hy3-preview (295B-A21B)",
        release="",
        tech="",
        family="moe",
        vocab=128000,
        ctx=131072,
        n_layer=48,
        n_head=64,
        n_kv=8,
        n_embd=5120,
        head_dim=128,
        n_experts=256,
        top_k=8,
        moe_inter=1536,
        n_shared=1,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=1,
        desc="Tencent Hunyuan 3 (preview): sparse MoE with a shared expert. Config approximate.",
    ),
    dict(
        module="command_a_plus",
        slug="command-a-plus",
        name="Command A+ (218B-A25B)",
        release="",
        tech="",
        family="moe",
        vocab=256000,
        ctx=131072,
        n_layer=48,
        n_head=64,
        n_kv=8,
        n_embd=6144,
        head_dim=128,
        n_experts=64,
        top_k=8,
        moe_inter=2048,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="Command A+: Cohere sparse MoE. Config approximate.",
    ),
    dict(
        module="lfm2_5_8b_a1b",
        slug="lfm2.5-8b-a1b",
        name="LFM2.5 (8B-A1B)",
        release="",
        tech="",
        family="moe",
        vocab=65536,
        ctx=32768,
        n_layer=24,
        n_head=32,
        n_kv=8,
        n_embd=2048,
        head_dim=128,
        n_experts=64,
        top_k=4,
        moe_inter=1024,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="True",
        tiny_shared=0,
        desc="LFM2.5 8B-A1B: modeled as a sparse MoE transformer.\nNOTE: Liquid LFM2 actually uses short-conv + attention/LIV-style mixers; this is a MoE transformer approximation.",
    ),
    dict(
        module="mellum2_thinking",
        slug="mellum2-thinking",
        name="JetBrains Mellum2 Thinking (12B-A2.5B)",
        release="",
        tech="",
        family="moe",
        vocab=128256,
        ctx=32768,
        n_layer=32,
        n_head=32,
        n_kv=8,
        n_embd=2560,
        head_dim=128,
        n_experts=64,
        top_k=6,
        moe_inter=1024,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="JetBrains Mellum2 Thinking: a code-focused sparse MoE. Config approximate.",
    ),
    dict(
        module="laguna_xs_2",
        slug="laguna-xs.2",
        name="Laguna XS.2 (33B)",
        release="2026-04-28",
        tech="https://poolside.ai/assets/laguna/laguna-m1-xs2-technical-report.pdf",
        family="moe",
        vocab=128256,
        ctx=131072,
        n_layer=40,
        n_head=32,
        n_kv=8,
        n_embd=4096,
        head_dim=128,
        n_experts=64,
        top_k=6,
        moe_inter=1024,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="Laguna XS.2: MoE with gated GQA and a 1 full / 3 sliding-window schedule.\nConfig approximate.",
    ),
    dict(
        module="zaya1_8b",
        slug="zaya1-8b",
        name="ZAYA1-8B (8.4B)",
        release="2026-05-06",
        tech="https://arxiv.org/abs/2605.05365",
        family="moe",
        vocab=128256,
        ctx=32768,
        n_layer=32,
        n_head=32,
        n_kv=8,
        n_embd=4096,
        head_dim=128,
        n_experts=64,
        top_k=1,
        moe_inter=2048,
        n_shared=0,
        qk_norm="False",
        theta="1000000.0",
        eps="1e-5",
        tie="False",
        tiny_shared=0,
        desc="ZAYA1-8B: MoE with top-1 routing. ASSUMPTION: the CCA (compressed convolutional\nattention) is replaced by GQA here. Config approximate.",
    ),
    dict(
        module="gemma4_26b_a4b",
        slug="gemma4-26b-a4b",
        name="Gemma 4 (26B-A4B)",
        release="2026-04-02",
        tech="https://ai.google.dev/gemma/docs/core/model_card_4",
        family="moe",
        vocab=262144,
        ctx=131072,
        n_layer=48,
        n_head=32,
        n_kv=16,
        n_embd=4096,
        head_dim=128,
        n_experts=128,
        top_k=8,
        moe_inter=1024,
        n_shared=0,
        qk_norm="True",
        theta="1000000.0",
        eps="1e-6",
        tie="True",
        tiny_shared=0,
        desc="Gemma 4 26B-A4B: a Gemma-flavored sparse MoE. ASSUMPTION: modeled with the generic MoE\nlayer; Gemma's sandwich norm + sliding/global schedule are omitted. Config approximate.",
    ),
]

# Corrections emitted by scripts/audit_fidelity.py --emit-specs from the committed
# HF config fixtures. These keep the historical hand-written SPECS readable while
# making the generated real presets follow published config.json dimensions.
SPEC_OVERRIDES = {
    "deepseek-r1": {"ctx": 163840},
    "llama4-maverick": {"ctx": 1000000, "inter": 8192, "moe_every": 2},
    "kimi-k2": {"ctx": 131072, "theta": 50000.0, "scaling": 2.827},
    "gemma3-270m": {"ctx": 128000},
    "grok-2.5": {"theta": 208533496},
    "minimax-m2": {"ctx": 196608, "n_embd": 3072, "theta": 5000000, "eps": 1e-06},
    "olmo3-32b": {"ctx": 65536, "vocab": 100278, "inter": 27648, "window": 4096, "global_every": 4},
    "olmo3-7b": {"ctx": 65536, "vocab": 100278, "window": 4096, "global_every": 4},
    "deepseek-v3.2": {"ctx": 163840},
    "mistral-large-3": {"ctx": 262144},
    "mimo-v2-flash": {
        "ctx": 262144,
        "vocab": 152576,
        "n_kv": 4,
        "n_embd": 4096,
        "head_dim": 192,
        "moe_inter": 2048,
        "n_experts": 256,
        "theta": 5000000,
    },
    "glm-4.7": {"ctx": 202752},
    "glm-5": {
        "ctx": 202752,
        "vocab": 154880,
        "n_layer": 78,
        "n_head": 64,
        "n_embd": 6144,
        "moe_inter": 2048,
        "n_experts": 256,
        "q_lora": 2048,
        "qk_nope": 192,
        "v_head": 256,
    },
    "nemotron3-super-120b": {
        "ctx": 262144,
        "n_layer": 88,
        "n_head": 32,
        "n_kv": 2,
        "n_embd": 4096,
        "inter": 2688,
        "moe_inter": 2688,
        "n_experts": 512,
        "top_k": 22,
        "theta": 10000,
    },
    "gemma4-31b": {"ctx": 262144, "n_layer": 60, "head_dim": 256},
    "gemma4-26b-a4b": {
        "ctx": 262144,
        "n_layer": 30,
        "n_head": 16,
        "n_kv": 8,
        "n_embd": 2816,
        "head_dim": 256,
        "moe_inter": 704,
    },
    "gemma4-12b": {"ctx": 262144},
    "llama3.2-3b": {"ctx": 128000},
    "qwen3-coder-flash": {"ctx": 262144, "theta": 10000000},
    "kimi-k2.5": {"ctx": 262144, "theta": 50000.0, "eps": 1e-05, "scaling": 2.827},
    "step-3.5-flash": {
        "ctx": 262144,
        "vocab": 128896,
        "n_layer": 45,
        "n_embd": 4096,
        "moe_inter": 1280,
        "window": 512,
        "global_every": 4,
        "global_first": True,
        "attention_gate": True,
    },
    "nanbeige-4.1": {
        "ctx": 262144,
        "vocab": 166144,
        "n_layer": 32,
        "n_head": 20,
        "n_kv": 4,
        "n_embd": 2560,
        "inter": 10496,
        "theta": 70000000,
        "tie": False,
    },
    "minimax-m2.5": {"ctx": 196608, "n_embd": 3072, "theta": 5000000, "eps": 1e-06},
    "ling-2.5": {
        "ctx": 131072,
        "vocab": 157184,
        "n_layer": 80,
        "n_head": 64,
        "n_kv": 64,
        "n_embd": 8192,
        "moe_inter": 2048,
        "theta": 6000000,
        "eps": 1e-06,
    },
    "qwen3.5": {
        "ctx": 262144,
        "vocab": 248320,
        "n_layer": 60,
        "n_kv": 2,
        "head_dim": 256,
        "moe_inter": 1024,
    },
    "sarvam-30b": {
        "ctx": 131072,
        "vocab": 262144,
        "n_layer": 19,
        "n_head": 64,
        "n_embd": 4096,
        "head_dim": 64,
        "moe_inter": 1024,
        "top_k": 6,
        "n_shared": 1,
        "theta": 8000000,
    },
    "sarvam-105b": {
        "ctx": 131072,
        "vocab": 262144,
        "n_layer": 32,
        "n_embd": 4096,
        "n_experts": 128,
        "first_k_dense": 1,
        "theta": 10000.0,
        "dense_inter": 16384,
    },
    "phi-4": {"tie": False},
    "longcat-flash-lite": {
        "ctx": 327680,
        "n_head": 32,
        "n_embd": 3072,
        "theta": 5000000.0,
        "scaling": 6.0,
    },
    "mistral-small-4": {
        "ctx": 1048576,
        "n_layer": 36,
        "n_head": 32,
        "n_embd": 4096,
        "moe_inter": 2048,
        "top_k": 4,
        "first_k_dense": 0,
        "q_lora": 1024,
        "kv_lora": 256,
        "qk_nope": 64,
        "eps": 1e-06,
        "scaling": 1.0,
    },
    "nemotron3-nano-4b": {
        "ctx": 262144,
        "n_layer": 42,
        "n_head": 40,
        "n_kv": 8,
        "n_embd": 3136,
        "inter": 12544,
        "tie": False,
    },
    "minimax-m2.7": {"ctx": 204800, "n_embd": 3072, "theta": 5000000, "eps": 1e-06},
    "gemma4-e2b": {"n_layer": 35, "n_embd": 1536, "inter": 6144, "window": 512},
    "gemma4-e4b": {"n_layer": 42, "n_head": 8, "n_kv": 2, "window": 512},
    "deepseek-v4-flash": {
        "ctx": 1048576,
        "n_layer": 43,
        "n_head": 64,
        "n_embd": 4096,
        "top_k": 6,
        "q_lora": 1024,
        "scaling": 1.5,
    },
    "deepseek-v4-pro": {"ctx": 1048576, "moe_inter": 3072, "top_k": 6},
    "laguna-xs.2": {
        "ctx": 262144,
        "vocab": 100352,
        "n_head": 48,
        "n_embd": 2048,
        "moe_inter": 512,
        "n_experts": 256,
        "top_k": 8,
        "eps": 1e-06,
        "window": 512,
        "global_every": 4,
        "global_first": True,
        "attention_gate": True,
    },
    "zaya1-8b": {
        "ctx": 131072,
        "vocab": 262272,
        "n_layer": 40,
        "n_head": 8,
        "n_kv": 2,
        "n_embd": 2048,
        "n_experts": 16,
        "tie": True,
    },
    "glm-5.1": {
        "ctx": 202752,
        "vocab": 154880,
        "n_layer": 78,
        "n_head": 64,
        "n_embd": 6144,
        "moe_inter": 2048,
        "n_experts": 256,
        "q_lora": 2048,
        "qk_nope": 192,
        "v_head": 256,
    },
    "qwen3.6-35b-a3b": {
        "ctx": 262144,
        "vocab": 248320,
        "n_layer": 40,
        "head_dim": 256,
        "n_experts": 256,
    },
    "kimi-k2.6": {"ctx": 262144, "theta": 50000.0, "eps": 1e-05, "scaling": 2.827},
    "qwen3.6-27b": {
        "ctx": 262144,
        "vocab": 248320,
        "n_head": 24,
        "n_kv": 4,
        "head_dim": 256,
        "inter": 17408,
    },
    "mimo-v2.5": {
        "ctx": 1048576,
        "vocab": 152576,
        "n_kv": 4,
        "n_embd": 4096,
        "head_dim": 192,
        "moe_inter": 2048,
        "n_experts": 256,
        "theta": 10000000,
    },
    "mimo-v2.5-pro": {
        "ctx": 1048576,
        "vocab": 152576,
        "n_layer": 70,
        "n_head": 128,
        "n_embd": 6144,
        "head_dim": 192,
        "n_experts": 384,
        "theta": 10000000,
    },
    "ling-2.6": {
        "ctx": 262144,
        "vocab": 157184,
        "n_layer": 80,
        "n_head": 64,
        "n_kv": 64,
        "n_embd": 8192,
        "moe_inter": 2048,
        "theta": 6000000,
        "eps": 1e-06,
    },
    "hunyuan-3-preview": {
        "ctx": 262144,
        "vocab": 120832,
        "n_layer": 80,
        "n_embd": 4096,
        "n_experts": 192,
    },
    "granite-4.1": {"vocab": 100352, "n_layer": 64, "inter": 32768, "theta": 50000000},
    "command-a-plus": {
        "ctx": 200000,
        "vocab": 262144,
        "n_layer": 32,
        "n_head": 128,
        "n_embd": 4096,
        "n_experts": 128,
        "n_shared": 4,
        "theta": 50000,
    },
    "lfm2.5-1.2b": {"ctx": 128000, "n_head": 32, "inter": 12288},
    "lfm2.5-350m": {"ctx": 128000, "n_layer": 16, "n_head": 16, "n_kv": 8, "inter": 6656},
    "lfm2.5-8b-a1b": {"ctx": 128000, "vocab": 128000, "moe_inter": 1792, "n_experts": 32},
    "mellum2-thinking": {
        "ctx": 131072,
        "vocab": 98304,
        "n_layer": 28,
        "n_kv": 4,
        "n_embd": 2304,
        "moe_inter": 896,
        "top_k": 8,
        "eps": 1e-06,
    },
    "nemotron3-ultra": {
        "ctx": 262144,
        "n_kv": 2,
        "inter": 5120,
        "moe_inter": 5120,
        "n_experts": 512,
        "top_k": 22,
        "theta": 10000,
    },
}


def main() -> None:
    for s in SPECS:
        s = {**s, **SPEC_OVERRIDES.get(s["slug"], {})}
        if s["family"] == "moe":
            s.setdefault("inter", s["moe_inter"])
            s.setdefault("moe_every", 1)
            s.setdefault("nope_every", 0)
            s.setdefault("window", 0)
            s.setdefault("tiny_window", 0 if s["window"] == 0 else min(16, s["window"]))
            s.setdefault("global_every", 1)
            s.setdefault("global_first", False)
            s.setdefault("attention_gate", False)
            if s["slug"] == "llama4-maverick":
                s["nope_every"] = 4
            elif s["slug"] == "arcee-trinity-large":
                s["attention_gate"] = True
            elif s["slug"] == "mimo-v2-flash":
                s["window"] = 128
                s["tiny_window"] = 16
                s["global_every"] = s["n_layer"] + 1
        elif s["family"] == "mamba":
            if "layer_pattern" not in s:
                # Fallback for generated Mamba variants that predate explicit NemotronH patterns:
                # alternate mixer/FFN layers and keep the old periodic attention cadence visible.
                s["layer_pattern"] = "".join(
                    "*" if (i + 1) % s["attn_every"] == 0 else ("M" if i % 2 == 0 else "E")
                    for i in range(s["n_layer"])
                )
        elif s["family"] == "deltanet":
            s.setdefault("partial_rotary_factor", 0.25)
            s.setdefault("linear_conv_kernel_dim", 4)
        elif s["family"] == "olmo":
            s.setdefault("window", 0)
            s.setdefault("tiny_window", 0 if s["window"] == 0 else min(16, s["window"]))
            s.setdefault("global_every", 1)
        fam = s["family"]
        text = (
            _PREAMBLE.format(
                base=BASES[fam],
                family_desc=FAMILY_DESC[fam],
                ref=FAMILY_REF[fam],
                **s,
            )
            + CONFIG_TEMPLATES[fam].format(**s)
            + BODIES[fam]
        )
        (MODELS / f"{s['module']}.py").write_text(text)
        print(f"wrote llm_gallery/models/{s['module']}.py  ({fam}-style)")


if __name__ == "__main__":
    main()
