"""Gemma 3 (270M)

Gemma 3 270M: the smallest Gemma 3. Uses multi-query attention (MQA: a single shared K/V
head, n_kv_head=1) with the Gemma sliding/global + sandwich-norm recipe. See gemma3_27b.py.

Architecture : sliding-window + global attn · sandwich norm · QK-Norm · GeGLU
Reference    : gemma3_27b.py  ← read this first; all building blocks are annotated there

Diagram: https://sebastianraschka.com/llm-architecture-gallery (Gemma 3 (270M))
Tech report: https://arxiv.org/pdf/2503.19786

Self-contained: every module below is defined in THIS file. Generated by scripts/_gen_dense.py from
the validated gemma3_27b.py base — edit that base (or this generator) rather than hand-editing here.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F

MODEL_NAME = "Gemma 3 (270M)"
RELEASE_DATE = "2025-08-14"
GALLERY_URL = "https://sebastianraschka.com/llm-architecture-gallery"
TECH_REPORT_URL = "https://arxiv.org/pdf/2503.19786"


@dataclass
class Config:
    vocab_size: int = 262144
    context_length: int = 128000
    n_layer: int = 18
    n_head: int = 4
    n_kv_head: int = 1
    n_embd: int = 640
    head_dim: int = 256
    intermediate_size: int = 2048
    sliding_window: int = 512
    global_every: int = 6
    rope_theta_global: float = 1000000.0
    rope_theta_local: float = 10000.0
    query_pre_attn_scalar: int = 256
    norm_eps: float = 1e-6


PRESETS: dict[str, Config] = {
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=6, n_head=4, n_kv_head=1,
        n_embd=128, head_dim=32, intermediate_size=256, sliding_window=16, global_every=3,
        rope_theta_global=10000.0, rope_theta_local=10000.0, query_pre_attn_scalar=32,
    ),
    "gemma3-270m": Config(),
}
DEFAULT_PRESET = "gemma3-270m"


# --------------------------------------------------------------------------------------------------
# Building blocks
# --------------------------------------------------------------------------------------------------
class GemmaRMSNorm(nn.Module):
    """RMSNorm with Gemma's ``(1 + weight)`` gain (weight starts at zero -> identity gain)."""

    def __init__(self, dim: int, eps: float = 1e-6):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.zeros(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        dtype = x.dtype
        x = x.float()
        x = x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
        return (x * (1.0 + self.weight.float())).to(dtype)


def precompute_rope(head_dim: int, max_seq_len: int, theta: float):
    inv_freq = 1.0 / (theta ** (torch.arange(0, head_dim, 2).float() / head_dim))
    t = torch.arange(max_seq_len).float()
    freqs = torch.outer(t, inv_freq)
    emb = torch.cat([freqs, freqs], dim=-1)
    return emb.cos(), emb.sin()


def rotate_half(x: torch.Tensor) -> torch.Tensor:
    x1, x2 = x.chunk(2, dim=-1)
    return torch.cat((-x2, x1), dim=-1)


def apply_rope(q, k, cos, sin):
    cos, sin = cos[None, None], sin[None, None]
    return q * cos + rotate_half(q) * sin, k * cos + rotate_half(k) * sin


def repeat_kv(x: torch.Tensor, n_rep: int) -> torch.Tensor:
    if n_rep == 1:
        return x
    b, n_kv, t, hd = x.shape
    return x[:, :, None, :, :].expand(b, n_kv, n_rep, t, hd).reshape(b, n_kv * n_rep, t, hd)


class Attention(nn.Module):
    """GQA with per-head QK-Norm, decoupled head_dim, and a fixed Q scale (not 1/sqrt(hd))."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.n_head = cfg.n_head
        self.n_kv_head = cfg.n_kv_head
        self.n_rep = cfg.n_head // cfg.n_kv_head
        self.head_dim = cfg.head_dim
        self.scale = cfg.query_pre_attn_scalar ** -0.5  # Gemma scales Q by this (not 1/sqrt(hd))
        self.q_proj = nn.Linear(cfg.n_embd, self.n_head * self.head_dim, bias=False)
        self.k_proj = nn.Linear(cfg.n_embd, self.n_kv_head * self.head_dim, bias=False)
        self.v_proj = nn.Linear(cfg.n_embd, self.n_kv_head * self.head_dim, bias=False)
        self.o_proj = nn.Linear(self.n_head * self.head_dim, cfg.n_embd, bias=False)
        self.q_norm = GemmaRMSNorm(self.head_dim, cfg.norm_eps)
        self.k_norm = GemmaRMSNorm(self.head_dim, cfg.norm_eps)

    def forward(self, x, cos, sin, mask):
        b, t, _ = x.shape
        q = self.q_proj(x).view(b, t, self.n_head, self.head_dim).transpose(1, 2)
        k = self.k_proj(x).view(b, t, self.n_kv_head, self.head_dim).transpose(1, 2)
        v = self.v_proj(x).view(b, t, self.n_kv_head, self.head_dim).transpose(1, 2)

        q, k = self.q_norm(q), self.k_norm(k)
        q, k = apply_rope(q, k, cos, sin)
        k, v = repeat_kv(k, self.n_rep), repeat_kv(v, self.n_rep)

        att = (q @ k.transpose(-2, -1)) * self.scale
        att = att.masked_fill(mask[:t, :t], float("-inf"))
        att = F.softmax(att, dim=-1)
        y = (att @ v).transpose(1, 2).reshape(b, t, self.n_head * self.head_dim)
        return self.o_proj(y)


class GeGLU(nn.Module):
    """Gated MLP with tanh-approx GELU: down( gelu(gate(x)) * up(x) )."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.gate_proj = nn.Linear(cfg.n_embd, cfg.intermediate_size, bias=False)
        self.up_proj = nn.Linear(cfg.n_embd, cfg.intermediate_size, bias=False)
        self.down_proj = nn.Linear(cfg.intermediate_size, cfg.n_embd, bias=False)

    def forward(self, x):
        return self.down_proj(F.gelu(self.gate_proj(x), approximate="tanh") * self.up_proj(x))


class Block(nn.Module):
    """Sandwich-norm block: a norm both before AND after each sublayer (four norms total)."""

    def __init__(self, cfg: Config, is_global: bool):
        super().__init__()
        self.is_global = is_global
        self.input_norm = GemmaRMSNorm(cfg.n_embd, cfg.norm_eps)
        self.attn = Attention(cfg)
        self.post_attn_norm = GemmaRMSNorm(cfg.n_embd, cfg.norm_eps)
        self.pre_ffn_norm = GemmaRMSNorm(cfg.n_embd, cfg.norm_eps)
        self.ffn = GeGLU(cfg)
        self.post_ffn_norm = GemmaRMSNorm(cfg.n_embd, cfg.norm_eps)

    def forward(self, x, cos, sin, mask):
        x = x + self.post_attn_norm(self.attn(self.input_norm(x), cos, sin, mask))
        x = x + self.post_ffn_norm(self.ffn(self.pre_ffn_norm(x)))
        return x


# --------------------------------------------------------------------------------------------------
# Model
# --------------------------------------------------------------------------------------------------
class Model(nn.Module):
    """Full language model: scaled embeddings, sliding/global block stack, project to logits."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.config = cfg
        self.embed_scale = cfg.n_embd ** 0.5  # Gemma multiplies embeddings by sqrt(d_model)
        self.tok_emb = nn.Embedding(cfg.vocab_size, cfg.n_embd)
        # Layer i (0-indexed) is global if (i+1) is a multiple of global_every.
        self.blocks = nn.ModuleList(
            Block(cfg, is_global=((i + 1) % cfg.global_every == 0)) for i in range(cfg.n_layer)
        )
        self.norm = GemmaRMSNorm(cfg.n_embd, cfg.norm_eps)
        self.lm_head = nn.Linear(cfg.n_embd, cfg.vocab_size, bias=False)
        self.lm_head.weight = self.tok_emb.weight  # tied

        # Two RoPE tables: global layers and local (sliding) layers use different base frequencies.
        cg, sg = precompute_rope(cfg.head_dim, cfg.context_length, cfg.rope_theta_global)
        cl, sl = precompute_rope(cfg.head_dim, cfg.context_length, cfg.rope_theta_local)
        self.register_buffer("rope_cos_global", cg, persistent=False)
        self.register_buffer("rope_sin_global", sg, persistent=False)
        self.register_buffer("rope_cos_local", cl, persistent=False)
        self.register_buffer("rope_sin_local", sl, persistent=False)

        # Two masks: a full causal mask (global) and a sliding-window causal mask (local).
        n = cfg.context_length
        ar = torch.arange(n)
        future = ar[None, :] > ar[:, None]
        too_far = (ar[:, None] - ar[None, :]) >= cfg.sliding_window
        self.register_buffer("mask_global", future, persistent=False)
        self.register_buffer("mask_local", future | too_far, persistent=False)
        self.apply(self._init_weights)

    def _init_weights(self, m: nn.Module) -> None:
        if isinstance(m, (nn.Linear, nn.Embedding)):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)

    def forward(self, idx: torch.Tensor) -> torch.Tensor:
        b, t = idx.shape
        x = self.tok_emb(idx) * self.embed_scale
        for block in self.blocks:
            if block.is_global:
                cos, sin, mask = self.rope_cos_global[:t], self.rope_sin_global[:t], self.mask_global
            else:
                cos, sin, mask = self.rope_cos_local[:t], self.rope_sin_local[:t], self.mask_local
            x = block(x, cos, sin, mask)
        return self.lm_head(self.norm(x))


# --------------------------------------------------------------------------------------------------
# Standalone smoke test: `python llm_gallery/models/gemma3_27b.py`
# --------------------------------------------------------------------------------------------------
if __name__ == "__main__":
    torch.manual_seed(0)
    cfg = PRESETS["tiny"]
    model = Model(cfg)
    idx = torch.randint(0, cfg.vocab_size, (2, 16))
    logits = model(idx)
    loss = F.cross_entropy(logits.reshape(-1, logits.size(-1)), idx.reshape(-1))
    loss.backward()
    n_global = sum(b.is_global for b in model.blocks)
    print(f"{MODEL_NAME}  (tiny preset)")
    print(f"  params : {sum(p.numel() for p in model.parameters()):,}")
    print(f"  layers : {cfg.n_layer} ({n_global} global, {cfg.n_layer - n_global} sliding-window)")
    print(f"  logits : {tuple(logits.shape)}")
    print(f"  loss   : {loss.item():.4f}  (~ln(vocab)={math.log(cfg.vocab_size):.4f})")
