"""GPT-OSS (120B)

GPT-OSS 120B: the larger gpt-oss. MoE + alternating sliding/global attention +
attention sinks. Same architecture as gpt_oss_20b.py, scaled up.

Diagram: https://sebastianraschka.com/llm-architecture-gallery (GPT-OSS (120B))
Tech report: https://cdn.openai.com/pdf/419b6906-9da6-406c-a19d-1bb078ac7637/oai_gpt-oss_model_card.pdf

Self-contained: every module below is defined in THIS file. Generated by scripts/_gen_dense.py from
the validated gpt_oss_20b.py base — edit that base (or this generator) rather than hand-editing here.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F

MODEL_NAME = "GPT-OSS (120B)"
RELEASE_DATE = "2025-08-04"
GALLERY_URL = "https://sebastianraschka.com/llm-architecture-gallery"
TECH_REPORT_URL = "https://cdn.openai.com/pdf/419b6906-9da6-406c-a19d-1bb078ac7637/oai_gpt-oss_model_card.pdf"


@dataclass
class Config:
    vocab_size: int = 201088
    context_length: int = 131072
    n_layer: int = 36
    n_head: int = 64
    n_kv_head: int = 8
    n_embd: int = 2880
    head_dim: int = 64
    n_experts: int = 128
    n_experts_per_tok: int = 4
    moe_intermediate_size: int = 2880
    sliding_window: int = 128
    rope_theta: float = 150000.0
    norm_eps: float = 1e-5
    tie_embeddings: bool = False


PRESETS: dict[str, Config] = {
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=4, n_head=4, n_kv_head=2, n_embd=128,
        head_dim=32, n_experts=8, n_experts_per_tok=2, moe_intermediate_size=128,
        sliding_window=16, rope_theta=10000.0,
    ),
    "gpt-oss-120b": Config(),
}
DEFAULT_PRESET = "gpt-oss-120b"


class RMSNorm(nn.Module):
    def __init__(self, dim: int, eps: float = 1e-5):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        dtype = x.dtype
        x = x.float()
        x = x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
        return (x.to(dtype)) * self.weight


def precompute_rope(head_dim: int, max_seq_len: int, theta: float):
    inv_freq = 1.0 / (theta ** (torch.arange(0, head_dim, 2).float() / head_dim))
    freqs = torch.outer(torch.arange(max_seq_len).float(), inv_freq)
    emb = torch.cat([freqs, freqs], dim=-1)
    return emb.cos(), emb.sin()


def rotate_half(x: torch.Tensor) -> torch.Tensor:
    x1, x2 = x.chunk(2, dim=-1)
    return torch.cat((-x2, x1), dim=-1)


def apply_rope(q, k, cos, sin):
    cos, sin = cos[None, None], sin[None, None]
    return q * cos + rotate_half(q) * sin, k * cos + rotate_half(k) * sin


def repeat_kv(x: torch.Tensor, n_rep: int) -> torch.Tensor:
    if n_rep == 1:
        return x
    b, n_kv, t, hd = x.shape
    return x[:, :, None, :, :].expand(b, n_kv, n_rep, t, hd).reshape(b, n_kv * n_rep, t, hd)


class Attention(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()
        self.n_head, self.n_kv_head = cfg.n_head, cfg.n_kv_head
        self.n_rep = cfg.n_head // cfg.n_kv_head
        self.head_dim = cfg.head_dim
        self.q_proj = nn.Linear(cfg.n_embd, self.n_head * self.head_dim, bias=True)
        self.k_proj = nn.Linear(cfg.n_embd, self.n_kv_head * self.head_dim, bias=True)
        self.v_proj = nn.Linear(cfg.n_embd, self.n_kv_head * self.head_dim, bias=True)
        self.o_proj = nn.Linear(self.n_head * self.head_dim, cfg.n_embd, bias=True)
        # One learned "attention sink" logit per head (see forward).
        self.sinks = nn.Parameter(torch.zeros(self.n_head))

    def forward(self, x, cos, sin, mask):
        b, t, _ = x.shape
        q = self.q_proj(x).view(b, t, self.n_head, self.head_dim).transpose(1, 2)
        k = self.k_proj(x).view(b, t, self.n_kv_head, self.head_dim).transpose(1, 2)
        v = self.v_proj(x).view(b, t, self.n_kv_head, self.head_dim).transpose(1, 2)
        q, k = apply_rope(q, k, cos, sin)
        k, v = repeat_kv(k, self.n_rep), repeat_kv(v, self.n_rep)

        att = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)  # [B, nh, T, T]
        att = att.masked_fill(mask[:t, :t], float("-inf"))

        # Attention sink: append one extra logit per head, softmax over [keys, sink], then drop the
        # sink column. Probability that lands on the sink is simply discarded, so a head can choose to
        # attend less to real tokens.
        sink = self.sinks.view(1, -1, 1, 1).expand(b, -1, t, 1)  # [B, nh, T, 1]
        probs = F.softmax(torch.cat([att, sink], dim=-1), dim=-1)[..., :t]
        y = (probs @ v).transpose(1, 2).reshape(b, t, self.n_head * self.head_dim)
        return self.o_proj(y)


class Expert(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()
        self.gate_proj = nn.Linear(cfg.n_embd, cfg.moe_intermediate_size, bias=True)
        self.up_proj = nn.Linear(cfg.n_embd, cfg.moe_intermediate_size, bias=True)
        self.down_proj = nn.Linear(cfg.moe_intermediate_size, cfg.n_embd, bias=True)

    def forward(self, x):
        return self.down_proj(F.silu(self.gate_proj(x)) * self.up_proj(x))


class MoE(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()
        self.n_experts = cfg.n_experts
        self.top_k = cfg.n_experts_per_tok
        self.gate = nn.Linear(cfg.n_embd, cfg.n_experts, bias=True)
        self.experts = nn.ModuleList(Expert(cfg) for _ in range(cfg.n_experts))

    def forward(self, x):
        b, t, c = x.shape
        x = x.reshape(-1, c)
        topw, topi = F.softmax(self.gate(x), dim=-1).topk(self.top_k, dim=-1)
        topw = topw / topw.sum(dim=-1, keepdim=True)
        out = torch.zeros_like(x)
        for e in range(self.n_experts):
            sel = topi == e
            if not sel.any():
                continue
            tok_idx, slot = sel.nonzero(as_tuple=True)
            out[tok_idx] += topw[tok_idx, slot].unsqueeze(-1) * self.experts[e](x[tok_idx])
        return out.reshape(b, t, c)


class Block(nn.Module):
    def __init__(self, cfg: Config, is_local: bool):
        super().__init__()
        self.is_local = is_local
        self.attn_norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.attn = Attention(cfg)
        self.ffn_norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.moe = MoE(cfg)

    def forward(self, x, cos, sin, mask):
        x = x + self.attn(self.attn_norm(x), cos, sin, mask)
        x = x + self.moe(self.ffn_norm(x))
        return x


class Model(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()
        self.config = cfg
        self.tok_emb = nn.Embedding(cfg.vocab_size, cfg.n_embd)
        # Even layers use local (sliding-window) attention, odd layers use full attention.
        self.blocks = nn.ModuleList(Block(cfg, is_local=(i % 2 == 0)) for i in range(cfg.n_layer))
        self.norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.lm_head = nn.Linear(cfg.n_embd, cfg.vocab_size, bias=False)
        if cfg.tie_embeddings:
            self.lm_head.weight = self.tok_emb.weight

        cos, sin = precompute_rope(cfg.head_dim, cfg.context_length, cfg.rope_theta)
        self.register_buffer("rope_cos", cos, persistent=False)
        self.register_buffer("rope_sin", sin, persistent=False)
        n = cfg.context_length
        ar = torch.arange(n)
        future = ar[None, :] > ar[:, None]
        too_far = (ar[:, None] - ar[None, :]) >= cfg.sliding_window
        self.register_buffer("mask_global", future, persistent=False)
        self.register_buffer("mask_local", future | too_far, persistent=False)
        self.apply(self._init_weights)

    def _init_weights(self, m: nn.Module) -> None:
        if isinstance(m, nn.Linear):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, nn.Embedding):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)

    def forward(self, idx: torch.Tensor) -> torch.Tensor:
        b, t = idx.shape
        x = self.tok_emb(idx)
        cos, sin = self.rope_cos[:t], self.rope_sin[:t]
        for block in self.blocks:
            mask = self.mask_local if block.is_local else self.mask_global
            x = block(x, cos, sin, mask)
        return self.lm_head(self.norm(x))


if __name__ == "__main__":
    torch.manual_seed(0)
    cfg = PRESETS["tiny"]
    model = Model(cfg)
    idx = torch.randint(0, cfg.vocab_size, (2, 16))
    logits = model(idx)
    F.cross_entropy(logits.reshape(-1, logits.size(-1)), idx.reshape(-1)).backward()
    n_local = sum(b.is_local for b in model.blocks)
    print(f"{MODEL_NAME}  (tiny preset)")
    print(f"  attn   : {n_local} sliding-window + {cfg.n_layer - n_local} global layers, with sinks")
    print(f"  experts: {cfg.n_experts} total, top-{cfg.n_experts_per_tok}")
    print(f"  params : {sum(p.numel() for p in model.parameters()):,}")
    print(f"  logits : {tuple(logits.shape)}")
