"""LongCat-Flash-Lite (68.5B-A3B)

LongCat-Flash-Lite: an MLA + MoE model. Config approximate.

Architecture : Multi-head Latent Attention (MLA) · fine-grained MoE · shared experts
Reference    : deepseek_v3.py  ← read this first; all building blocks are annotated there

Diagram: https://sebastianraschka.com/llm-architecture-gallery (LongCat-Flash-Lite (68.5B-A3B))
Tech report: https://arxiv.org/abs/2601.21204

Self-contained: every module below is defined in THIS file. Generated by scripts/_gen_dense.py from
the validated deepseek_v3.py base — edit that base (or this generator) rather than hand-editing here.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F

MODEL_NAME = "LongCat-Flash-Lite (68.5B-A3B)"
RELEASE_DATE = "2026-01-28"
GALLERY_URL = "https://sebastianraschka.com/llm-architecture-gallery"
TECH_REPORT_URL = "https://arxiv.org/abs/2601.21204"


@dataclass
class Config:
    vocab_size: int = 131072
    context_length: int = 327680
    n_layer: int = 40
    n_embd: int = 3072
    n_head: int = 32
    q_lora_rank: int = 1536
    kv_lora_rank: int = 512
    qk_nope_head_dim: int = 128
    qk_rope_head_dim: int = 64
    v_head_dim: int = 128
    n_experts: int = 256
    n_experts_per_tok: int = 8
    n_shared_experts: int = 1
    moe_intermediate_size: int = 1024
    dense_intermediate_size: int = 8192
    first_k_dense: int = 1
    routed_scaling_factor: float = 6.0
    rope_theta: float = 5000000.0
    norm_eps: float = 1e-5
    tie_embeddings: bool = False


PRESETS: dict[str, Config] = {
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=4, n_embd=128, n_head=4,
        q_lora_rank=64, kv_lora_rank=32, qk_nope_head_dim=16, qk_rope_head_dim=16, v_head_dim=16,
        n_experts=8, n_experts_per_tok=2, n_shared_experts=1, moe_intermediate_size=128,
        dense_intermediate_size=256, first_k_dense=1, routed_scaling_factor=1.0, rope_theta=10000.0,
    ),
    "longcat-flash-lite": Config(),
}
DEFAULT_PRESET = "longcat-flash-lite"


# --------------------------------------------------------------------------------------------------
# Building blocks
# --------------------------------------------------------------------------------------------------
class RMSNorm(nn.Module):
    """Root-mean-square normalization; scales tokens without centering."""

    def __init__(self, dim: int, eps: float = 1e-6):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        dtype = x.dtype
        x = x.float()
        x = x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
        return (x.to(dtype)) * self.weight


def precompute_rope(head_dim: int, max_seq_len: int, theta: float):
    inv_freq = 1.0 / (theta ** (torch.arange(0, head_dim, 2).float() / head_dim))
    freqs = torch.outer(torch.arange(max_seq_len).float(), inv_freq)
    emb = torch.cat([freqs, freqs], dim=-1)
    return emb.cos(), emb.sin()


def rotate_half(x: torch.Tensor) -> torch.Tensor:
    x1, x2 = x.chunk(2, dim=-1)
    return torch.cat((-x2, x1), dim=-1)


def apply_rope(x: torch.Tensor, cos: torch.Tensor, sin: torch.Tensor) -> torch.Tensor:
    return x * cos[None, None] + rotate_half(x) * sin[None, None]


class MLA(nn.Module):
    """Multi-head Latent Attention with decoupled RoPE."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.n_head = cfg.n_head
        self.qk_nope = cfg.qk_nope_head_dim
        self.qk_rope = cfg.qk_rope_head_dim
        self.v_head_dim = cfg.v_head_dim
        self.q_head_dim = cfg.qk_nope_head_dim + cfg.qk_rope_head_dim
        self.scale = self.q_head_dim ** -0.5

        # Query: low-rank down-projection -> norm -> up-projection to all heads.
        self.q_a_proj = nn.Linear(cfg.n_embd, cfg.q_lora_rank, bias=False)
        self.q_a_norm = RMSNorm(cfg.q_lora_rank, cfg.norm_eps)
        self.q_b_proj = nn.Linear(cfg.q_lora_rank, self.n_head * self.q_head_dim, bias=False)

        # KV: down-project to [latent | shared rope-key]. Only this latent would be cached.
        self.kv_a_proj = nn.Linear(cfg.n_embd, cfg.kv_lora_rank + cfg.qk_rope_head_dim, bias=False)
        self.kv_a_norm = RMSNorm(cfg.kv_lora_rank, cfg.norm_eps)
        # up-project the latent to per-head [k_nope | v].
        self.kv_b_proj = nn.Linear(
            cfg.kv_lora_rank, self.n_head * (self.qk_nope + self.v_head_dim), bias=False
        )
        self.o_proj = nn.Linear(self.n_head * self.v_head_dim, cfg.n_embd, bias=False)

    def forward(self, x, cos, sin, mask):
        b, t, _ = x.shape

        # ---- queries ----
        q = self.q_b_proj(self.q_a_norm(self.q_a_proj(x)))  # [B, T, nh*q_head_dim]
        q = q.view(b, t, self.n_head, self.q_head_dim).transpose(1, 2)  # [B, nh, T, q_head_dim]
        q_nope, q_rope = q.split([self.qk_nope, self.qk_rope], dim=-1)

        # ---- compressed keys/values ----
        kv = self.kv_a_proj(x)  # [B, T, kv_lora_rank + qk_rope]
        kv_latent, k_rope = kv.split([self.kv_a_norm.weight.numel(), self.qk_rope], dim=-1)
        k_rope = k_rope.view(b, t, 1, self.qk_rope).transpose(1, 2)  # [B, 1, T, qk_rope] (shared)
        kv = self.kv_b_proj(self.kv_a_norm(kv_latent))
        kv = kv.view(b, t, self.n_head, self.qk_nope + self.v_head_dim).transpose(1, 2)
        k_nope, v = kv.split([self.qk_nope, self.v_head_dim], dim=-1)

        # ---- decoupled RoPE on just the rope parts, then assemble full q,k ----
        q_rope = apply_rope(q_rope, cos, sin)
        k_rope = apply_rope(k_rope, cos, sin).expand(b, self.n_head, t, self.qk_rope)
        q = torch.cat([q_nope, q_rope], dim=-1)  # [B, nh, T, q_head_dim]
        k = torch.cat([k_nope, k_rope], dim=-1)

        att = (q @ k.transpose(-2, -1)) * self.scale
        att = att.masked_fill(mask[:t, :t], float("-inf"))
        att = F.softmax(att, dim=-1)
        y = att @ v  # [B, nh, T, v_head_dim]
        y = y.transpose(1, 2).reshape(b, t, self.n_head * self.v_head_dim)
        return self.o_proj(y)


class MLP(nn.Module):
    """A SwiGLU MLP; used both as a dense layer and as a single expert (with a smaller hidden size)."""

    def __init__(self, n_embd: int, intermediate: int):
        super().__init__()
        self.gate_proj = nn.Linear(n_embd, intermediate, bias=False)
        self.up_proj = nn.Linear(n_embd, intermediate, bias=False)
        self.down_proj = nn.Linear(intermediate, n_embd, bias=False)

    def forward(self, x):
        return self.down_proj(F.silu(self.gate_proj(x)) * self.up_proj(x))


class DeepseekMoE(nn.Module):
    """Fine-grained routed experts + a shared always-on expert; sigmoid gating with top-k."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.top_k = cfg.n_experts_per_tok
        self.n_experts = cfg.n_experts
        self.scaling = cfg.routed_scaling_factor
        self.gate = nn.Linear(cfg.n_embd, cfg.n_experts, bias=False)
        self.experts = nn.ModuleList(
            MLP(cfg.n_embd, cfg.moe_intermediate_size) for _ in range(cfg.n_experts)
        )
        self.shared = (
            MLP(cfg.n_embd, cfg.moe_intermediate_size * cfg.n_shared_experts)
            if cfg.n_shared_experts > 0
            else None
        )

    def forward(self, x):
        b, t, c = x.shape
        x = x.reshape(-1, c)
        scores = self.gate(x).sigmoid()  # DeepSeek V3 uses sigmoid (not softmax) gating
        topw, topi = scores.topk(self.top_k, dim=-1)
        topw = topw / (topw.sum(dim=-1, keepdim=True) + 1e-20) * self.scaling
        out = torch.zeros_like(x)
        for e in range(self.n_experts):
            sel = topi == e
            if not sel.any():
                continue
            tok_idx, slot = sel.nonzero(as_tuple=True)
            out[tok_idx] += topw[tok_idx, slot].unsqueeze(-1) * self.experts[e](x[tok_idx])
        if self.shared is not None:
            out = out + self.shared(x)
        return out.reshape(b, t, c)


class Block(nn.Module):
    """Pre-norm block: MLA attention + dense MLP (early layers) or DeepseekMoE (later layers)."""

    def __init__(self, cfg: Config, layer_idx: int):
        super().__init__()
        self.attn_norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.attn = MLA(cfg)
        self.ffn_norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        # The first `first_k_dense` layers are dense; the rest are MoE.
        if layer_idx < cfg.first_k_dense:
            self.ffn = MLP(cfg.n_embd, cfg.dense_intermediate_size)
        else:
            self.ffn = DeepseekMoE(cfg)

    def forward(self, x, cos, sin, mask):
        x = x + self.attn(self.attn_norm(x), cos, sin, mask)
        x = x + self.ffn(self.ffn_norm(x))
        return x


# --------------------------------------------------------------------------------------------------
# Model
# --------------------------------------------------------------------------------------------------
class Model(nn.Module):
    """Full language model: embed tokens, run MLA+MoE blocks, project to logits."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.config = cfg
        self.tok_emb = nn.Embedding(cfg.vocab_size, cfg.n_embd)
        self.blocks = nn.ModuleList(Block(cfg, i) for i in range(cfg.n_layer))
        self.norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.lm_head = nn.Linear(cfg.n_embd, cfg.vocab_size, bias=False)
        if cfg.tie_embeddings:
            self.lm_head.weight = self.tok_emb.weight

        # RoPE tables sized to the *rope* head dim only (the decoupled part).
        cos, sin = precompute_rope(cfg.qk_rope_head_dim, cfg.context_length, cfg.rope_theta)
        self.register_buffer("rope_cos", cos, persistent=False)
        self.register_buffer("rope_sin", sin, persistent=False)
        causal = torch.triu(
            torch.ones(cfg.context_length, cfg.context_length, dtype=torch.bool), diagonal=1
        )
        self.register_buffer("causal_mask", causal, persistent=False)
        self.apply(self._init_weights)

    def _init_weights(self, m: nn.Module) -> None:
        if isinstance(m, (nn.Linear, nn.Embedding)):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)

    def forward(self, idx: torch.Tensor) -> torch.Tensor:
        b, t = idx.shape
        x = self.tok_emb(idx)
        cos, sin = self.rope_cos[:t], self.rope_sin[:t]
        for block in self.blocks:
            x = block(x, cos, sin, self.causal_mask)
        return self.lm_head(self.norm(x))


# --------------------------------------------------------------------------------------------------
# Standalone smoke test: `python llm_gallery/models/deepseek_v3.py`
# --------------------------------------------------------------------------------------------------
if __name__ == "__main__":
    torch.manual_seed(0)
    cfg = PRESETS["tiny"]
    model = Model(cfg)
    idx = torch.randint(0, cfg.vocab_size, (2, 16))
    logits = model(idx)
    loss = F.cross_entropy(logits.reshape(-1, logits.size(-1)), idx.reshape(-1))
    loss.backward()
    n_dense = min(cfg.first_k_dense, cfg.n_layer)
    print(f"{MODEL_NAME}  (tiny preset)")
    print(f"  MLA     : q_head_dim={cfg.qk_nope_head_dim}+{cfg.qk_rope_head_dim}, kv_latent={cfg.kv_lora_rank}")
    print(f"  layers  : {n_dense} dense + {cfg.n_layer - n_dense} MoE ({cfg.n_experts} experts, +{cfg.n_shared_experts} shared)")
    print(f"  params  : {sum(p.numel() for p in model.parameters()):,}")
    print(f"  logits  : {tuple(logits.shape)}")
    print(f"  loss    : {loss.item():.4f}  (~ln(vocab)={math.log(cfg.vocab_size):.4f})")
