"""MiniMax M2 (230B)

MiniMax M2: fine-grained MoE (many experts) with GQA + QK-Norm. Config approximate.

Architecture : GQA · top-k sparse MoE · RoPE · SwiGLU · RMSNorm
Reference    : qwen3_30b_a3b.py  ← read this first; all building blocks are annotated there

Diagram: https://sebastianraschka.com/llm-architecture-gallery (MiniMax M2 (230B))
Tech report: https://arxiv.org/abs/2605.26494

Self-contained: every module below is defined in THIS file. Generated by scripts/_gen_dense.py from
the validated qwen3_30b_a3b.py base — edit that base (or this generator) rather than hand-editing here.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F

MODEL_NAME = "MiniMax M2 (230B)"
RELEASE_DATE = "2025-10-23"
GALLERY_URL = "https://sebastianraschka.com/llm-architecture-gallery"
TECH_REPORT_URL = "https://arxiv.org/abs/2605.26494"


@dataclass
class Config:
    vocab_size: int = 200064
    context_length: int = 196608
    n_layer: int = 62
    n_head: int = 48
    n_kv_head: int = 8
    n_embd: int = 3072
    head_dim: int = 128
    n_experts: int = 256
    n_experts_per_tok: int = 8
    moe_intermediate_size: int = 1536
    intermediate_size: int = 1536
    n_shared_experts: int = 0
    norm_topk_prob: bool = True
    moe_every: int = 1
    qk_norm: bool = True
    rope_theta: float = 5000000
    nope_every: int = 0
    sliding_window: int = 0
    global_every: int = 1
    global_first: bool = False
    attention_gate: bool = False
    norm_eps: float = 1e-06
    tie_embeddings: bool = False


PRESETS: dict[str, Config] = {
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=4, n_head=4, n_kv_head=2, n_embd=128,
        head_dim=32, n_experts=8, n_experts_per_tok=2, moe_intermediate_size=128,
        intermediate_size=256, n_shared_experts=0, moe_every=1,
        qk_norm=True, rope_theta=10000.0, nope_every=0, sliding_window=0,
        global_every=1, global_first=False, attention_gate=False,
        tie_embeddings=False,
    ),
    "minimax-m2": Config(),
}
DEFAULT_PRESET = "minimax-m2"


# --------------------------------------------------------------------------------------------------
# Building blocks
# --------------------------------------------------------------------------------------------------
class RMSNorm(nn.Module):
    """Root-mean-square normalization; scales tokens without centering."""

    def __init__(self, dim: int, eps: float = 1e-6):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        dtype = x.dtype
        x = x.float()
        x = x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
        return (x.to(dtype)) * self.weight


def precompute_rope(head_dim: int, max_seq_len: int, theta: float):
    inv_freq = 1.0 / (theta ** (torch.arange(0, head_dim, 2).float() / head_dim))
    freqs = torch.outer(torch.arange(max_seq_len).float(), inv_freq)
    emb = torch.cat([freqs, freqs], dim=-1)
    return emb.cos(), emb.sin()


def rotate_half(x: torch.Tensor) -> torch.Tensor:
    x1, x2 = x.chunk(2, dim=-1)
    return torch.cat((-x2, x1), dim=-1)


def apply_rope(q, k, cos, sin):
    cos, sin = cos[None, None], sin[None, None]
    return q * cos + rotate_half(q) * sin, k * cos + rotate_half(k) * sin


def repeat_kv(x: torch.Tensor, n_rep: int) -> torch.Tensor:
    if n_rep == 1:
        return x
    b, n_kv, t, hd = x.shape
    return x[:, :, None, :, :].expand(b, n_kv, n_rep, t, hd).reshape(b, n_kv * n_rep, t, hd)


class Attention(nn.Module):
    """GQA with optional per-head QK-Norm (enabled by cfg.qk_norm); same for all MoE layers."""

    def __init__(self, cfg: Config, use_rope: bool):
        super().__init__()
        self.use_rope = use_rope
        self.attention_gate = cfg.attention_gate
        self.n_head, self.n_kv_head = cfg.n_head, cfg.n_kv_head
        self.n_rep = cfg.n_head // cfg.n_kv_head
        self.head_dim = cfg.head_dim
        self.q_proj = nn.Linear(cfg.n_embd, self.n_head * self.head_dim, bias=False)
        self.k_proj = nn.Linear(cfg.n_embd, self.n_kv_head * self.head_dim, bias=False)
        self.v_proj = nn.Linear(cfg.n_embd, self.n_kv_head * self.head_dim, bias=False)
        self.o_proj = nn.Linear(self.n_head * self.head_dim, cfg.n_embd, bias=False)
        self.g_proj = (
            nn.Linear(cfg.n_embd, self.n_head * self.head_dim, bias=False)
            if cfg.attention_gate else None
        )
        self.q_norm = RMSNorm(self.head_dim, cfg.norm_eps) if cfg.qk_norm else None
        self.k_norm = RMSNorm(self.head_dim, cfg.norm_eps) if cfg.qk_norm else None

    def forward(self, x, cos, sin, mask):
        b, t, _ = x.shape
        q = self.q_proj(x).view(b, t, self.n_head, self.head_dim).transpose(1, 2)
        k = self.k_proj(x).view(b, t, self.n_kv_head, self.head_dim).transpose(1, 2)
        v = self.v_proj(x).view(b, t, self.n_kv_head, self.head_dim).transpose(1, 2)
        if self.q_norm is not None:
            q, k = self.q_norm(q), self.k_norm(k)
        if self.use_rope:
            q, k = apply_rope(q, k, cos, sin)
        k, v = repeat_kv(k, self.n_rep), repeat_kv(v, self.n_rep)
        att = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)
        att = att.masked_fill(mask[:t, :t], float("-inf"))
        att = F.softmax(att, dim=-1)
        y = (att @ v).transpose(1, 2).reshape(b, t, self.n_head * self.head_dim)
        if self.g_proj is not None:
            y = y * torch.sigmoid(self.g_proj(x))
        return self.o_proj(y)


class Expert(nn.Module):
    """One expert is just a SwiGLU MLP (with the small per-expert hidden size)."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.gate_proj = nn.Linear(cfg.n_embd, cfg.moe_intermediate_size, bias=False)
        self.up_proj = nn.Linear(cfg.n_embd, cfg.moe_intermediate_size, bias=False)
        self.down_proj = nn.Linear(cfg.moe_intermediate_size, cfg.n_embd, bias=False)

    def forward(self, x):
        return self.down_proj(F.silu(self.gate_proj(x)) * self.up_proj(x))


class DenseMLP(nn.Module):
    """Dense SwiGLU FFN used in interleaved MoE stacks such as Llama 4 Maverick."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.gate_proj = nn.Linear(cfg.n_embd, cfg.intermediate_size, bias=False)
        self.up_proj = nn.Linear(cfg.n_embd, cfg.intermediate_size, bias=False)
        self.down_proj = nn.Linear(cfg.intermediate_size, cfg.n_embd, bias=False)

    def forward(self, x):
        return self.down_proj(F.silu(self.gate_proj(x)) * self.up_proj(x))


class MoE(nn.Module):
    """Sparse mixture of experts with token-choice top-k routing."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.n_experts = cfg.n_experts
        self.top_k = cfg.n_experts_per_tok
        self.norm_topk = cfg.norm_topk_prob
        self.gate = nn.Linear(cfg.n_embd, cfg.n_experts, bias=False)  # the router
        self.experts = nn.ModuleList(Expert(cfg) for _ in range(cfg.n_experts))
        # Optional always-on "shared" expert(s): one wider SwiGLU applied to every token.
        self.shared = None
        if cfg.n_shared_experts > 0:
            shared_cfg = Config(**{**cfg.__dict__})
            shared_cfg.moe_intermediate_size = cfg.moe_intermediate_size * cfg.n_shared_experts
            self.shared = Expert(shared_cfg)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        b, t, c = x.shape
        x = x.reshape(-1, c)  # [N, C] flatten tokens; routing is per-token

        router_logits = self.gate(x)  # [N, E]
        probs = F.softmax(router_logits, dim=-1)
        topw, topi = probs.topk(self.top_k, dim=-1)  # [N, k] weights and expert indices
        if self.norm_topk:
            topw = topw / topw.sum(dim=-1, keepdim=True)

        out = torch.zeros_like(x)
        # Loop over experts (readable; in production you'd batch this). For expert e, find every
        # (token, slot) that routed to it, run the expert once on those tokens, and scatter-add the
        # router-weighted result back. A token routes to e at most once, so indices are unique.
        for e in range(self.n_experts):
            sel = topi == e  # [N, k] bool
            if not sel.any():
                continue
            tok_idx, slot = sel.nonzero(as_tuple=True)  # which tokens, and which of their k slots
            weight = topw[tok_idx, slot].unsqueeze(-1)  # [n_sel, 1]
            out[tok_idx] += weight * self.experts[e](x[tok_idx])

        if self.shared is not None:
            out = out + self.shared(x)
        return out.reshape(b, t, c)


class Block(nn.Module):
    """Pre-norm block: GQA attention + MoE or dense feed-forward, both with residual connections."""

    def __init__(self, cfg: Config, layer_idx: int):
        super().__init__()
        self.is_moe = layer_idx % cfg.moe_every == 0
        self.is_global = (
            cfg.sliding_window <= 0
            or (layer_idx % cfg.global_every == 0 if cfg.global_first else (layer_idx + 1) % cfg.global_every == 0)
        )
        use_rope = cfg.nope_every <= 0 or (layer_idx + 1) % cfg.nope_every != 0
        self.attn_norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.attn = Attention(cfg, use_rope)
        self.ffn_norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.ffn = MoE(cfg) if self.is_moe else DenseMLP(cfg)

    def forward(self, x, cos, sin, mask):
        x = x + self.attn(self.attn_norm(x), cos, sin, mask)
        x = x + self.ffn(self.ffn_norm(x))
        return x


# --------------------------------------------------------------------------------------------------
# Model
# --------------------------------------------------------------------------------------------------
class Model(nn.Module):
    """Full language model: embed tokens, run MoE blocks, project to logits."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.config = cfg
        self.tok_emb = nn.Embedding(cfg.vocab_size, cfg.n_embd)
        self.blocks = nn.ModuleList(Block(cfg, i) for i in range(cfg.n_layer))
        self.norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.lm_head = nn.Linear(cfg.n_embd, cfg.vocab_size, bias=False)
        if cfg.tie_embeddings:
            self.lm_head.weight = self.tok_emb.weight
        cos, sin = precompute_rope(cfg.head_dim, cfg.context_length, cfg.rope_theta)
        self.register_buffer("rope_cos", cos, persistent=False)
        self.register_buffer("rope_sin", sin, persistent=False)
        n = cfg.context_length
        ar = torch.arange(n)
        future = ar[None, :] > ar[:, None]
        if cfg.sliding_window > 0:
            too_far = (ar[:, None] - ar[None, :]) >= cfg.sliding_window
            self.register_buffer("mask_local", future | too_far, persistent=False)
        else:
            self.register_buffer("mask_local", future, persistent=False)
        self.register_buffer("mask_global", future, persistent=False)
        self.apply(self._init_weights)

    def _init_weights(self, m: nn.Module) -> None:
        if isinstance(m, (nn.Linear, nn.Embedding)):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)

    def forward(self, idx: torch.Tensor) -> torch.Tensor:
        b, t = idx.shape
        x = self.tok_emb(idx)
        cos, sin = self.rope_cos[:t], self.rope_sin[:t]
        for block in self.blocks:
            mask = self.mask_global if block.is_global else self.mask_local
            x = block(x, cos, sin, mask)
        return self.lm_head(self.norm(x))


# --------------------------------------------------------------------------------------------------
# Standalone smoke test: `python llm_gallery/models/qwen3_30b_a3b.py`
# --------------------------------------------------------------------------------------------------
if __name__ == "__main__":
    torch.manual_seed(0)
    cfg = PRESETS["tiny"]
    model = Model(cfg)
    idx = torch.randint(0, cfg.vocab_size, (2, 16))
    logits = model(idx)
    loss = F.cross_entropy(logits.reshape(-1, logits.size(-1)), idx.reshape(-1))
    loss.backward()
    total = sum(p.numel() for p in model.parameters())
    # "active" params: non-expert params + only top_k of the experts per layer.
    print(f"{MODEL_NAME}  (tiny preset)")
    print(f"  experts : {cfg.n_experts} total, top-{cfg.n_experts_per_tok} active per token")
    print(f"  params  : {total:,} total")
    print(f"  logits  : {tuple(logits.shape)}")
    print(f"  loss    : {loss.item():.4f}")
