"""Nemotron 3 Ultra (550B-A55B)

Nemotron 3 Ultra: the largest Nemotron — sparse hybrid Mamba + MoE. Config approximate.

Architecture : Mamba-2 SSM · periodic GQA hybrid · sparse MoE · RMSNorm
Reference    : nemotron3_nano_30b.py  ← read this first; all building blocks are annotated there

Diagram: https://sebastianraschka.com/llm-architecture-gallery (Nemotron 3 Ultra (550B-A55B))
Tech report: https://research.nvidia.com/labs/nemotron/files/NVIDIA-Nemotron-3-Ultra-Technical-Report.pdf

Self-contained: every module below is defined in THIS file. Generated by scripts/_gen_dense.py from
the validated nemotron3_nano_30b.py base — edit that base (or this generator) rather than hand-editing here.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F

MODEL_NAME = "Nemotron 3 Ultra (550B-A55B)"
RELEASE_DATE = ""
GALLERY_URL = "https://sebastianraschka.com/llm-architecture-gallery"
TECH_REPORT_URL = "https://research.nvidia.com/labs/nemotron/files/NVIDIA-Nemotron-3-Ultra-Technical-Report.pdf"


@dataclass
class Config:
    vocab_size: int = 131072
    context_length: int = 262144
    n_layer: int = 80
    n_embd: int = 8192
    n_head: int = 64
    n_kv_head: int = 2
    head_dim: int = 128
    rope_theta: float = 10000
    layer_pattern: str = "MEMEM*MEMEM*MEMEM*MEMEM*MEMEM*MEMEM*MEMEM*MEMEM*MEMEM*MEMEM*MEMEM*MEMEM*MEMEM*ME"
    mamba_expand: int = 2
    mamba_d_state: int = 128
    mamba_d_conv: int = 4
    mamba_dt_rank: int = 128
    use_moe: bool = True
    n_experts: int = 512
    n_experts_per_tok: int = 22
    moe_intermediate_size: int = 5120
    n_shared_experts: int = 1
    intermediate_size: int = 5120
    norm_eps: float = 1e-5
    tie_embeddings: bool = False


PRESETS: dict[str, Config] = {
    "tiny": Config(
        vocab_size=65, context_length=128, n_layer=6, n_embd=128, n_head=4, n_kv_head=2,
        head_dim=32, rope_theta=10000.0, layer_pattern="ME*MEM", mamba_expand=2,
        mamba_d_state=8, mamba_d_conv=4, mamba_dt_rank=16, use_moe=True, n_experts=8,
        n_experts_per_tok=2, moe_intermediate_size=128, n_shared_experts=1, intermediate_size=256,
    ),
    "nemotron3-ultra": Config(),
}
DEFAULT_PRESET = "nemotron3-ultra"


# --------------------------------------------------------------------------------------------------
# Building blocks
# --------------------------------------------------------------------------------------------------
class RMSNorm(nn.Module):
    """Root-mean-square normalization; scales tokens without centering."""

    def __init__(self, dim: int, eps: float = 1e-5):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        dtype = x.dtype
        x = x.float()
        x = x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
        return (x.to(dtype)) * self.weight


# --------------------------------------------------------------------------------------------------
# Mamba-2 selective SSM
# --------------------------------------------------------------------------------------------------
class Mamba(nn.Module):
    """Selective state-space model: input-dependent gating of a linear recurrence (Mamba-2 style)."""
    def __init__(self, cfg: Config):
        super().__init__()
        self.d_inner = cfg.mamba_expand * cfg.n_embd
        self.d_state = cfg.mamba_d_state
        self.dt_rank = cfg.mamba_dt_rank
        self.in_proj = nn.Linear(cfg.n_embd, 2 * self.d_inner, bias=False)  # -> (x, gate z)
        self.conv1d = nn.Conv1d(
            self.d_inner, self.d_inner, kernel_size=cfg.mamba_d_conv,
            groups=self.d_inner, padding=cfg.mamba_d_conv - 1,  # causal: pad left, trim right
        )
        self.x_proj = nn.Linear(self.d_inner, self.dt_rank + 2 * self.d_state, bias=False)
        self.dt_proj = nn.Linear(self.dt_rank, self.d_inner)
        self.A_log = nn.Parameter(torch.log(torch.arange(1, self.d_state + 1).float()).repeat(self.d_inner, 1))
        self.D = nn.Parameter(torch.ones(self.d_inner))
        self.out_proj = nn.Linear(self.d_inner, cfg.n_embd, bias=False)
        self.k_conv = cfg.mamba_d_conv

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        b, t, _ = x.shape
        x_in, z = self.in_proj(x).chunk(2, dim=-1)  # each [B, T, d_inner]

        # short causal depthwise conv over time
        x_in = self.conv1d(x_in.transpose(1, 2))[..., :t].transpose(1, 2)
        x_in = F.silu(x_in)

        # input-dependent Δ, B, C
        dbl = self.x_proj(x_in)
        dt, B, C = dbl.split([self.dt_rank, self.d_state, self.d_state], dim=-1)
        dt = F.softplus(self.dt_proj(dt))  # [B, T, d_inner]
        A = -torch.exp(self.A_log)  # [d_inner, d_state], negative -> stable decay

        h = x.new_zeros(b, self.d_inner, self.d_state)
        ys = []
        for s in range(t):
            dt_s = dt[:, s].unsqueeze(-1)  # [B, d_inner, 1]
            dA = torch.exp(dt_s * A)  # [B, d_inner, d_state]
            dBx = dt_s * B[:, s].unsqueeze(1) * x_in[:, s].unsqueeze(-1)  # [B, d_inner, d_state]
            h = dA * h + dBx
            ys.append((h * C[:, s].unsqueeze(1)).sum(-1))  # [B, d_inner]
        y = torch.stack(ys, dim=1)  # [B, T, d_inner]
        y = y + x_in * self.D
        y = y * F.silu(z)  # gate
        return self.out_proj(y)


# --------------------------------------------------------------------------------------------------
# GQA attention (hybrid layers)
# --------------------------------------------------------------------------------------------------
def precompute_rope(head_dim, max_seq_len, theta):
    inv_freq = 1.0 / (theta ** (torch.arange(0, head_dim, 2).float() / head_dim))
    freqs = torch.outer(torch.arange(max_seq_len).float(), inv_freq)
    emb = torch.cat([freqs, freqs], dim=-1)
    return emb.cos(), emb.sin()


def rotate_half(x):
    x1, x2 = x.chunk(2, dim=-1)
    return torch.cat((-x2, x1), dim=-1)


def apply_rope(q, k, cos, sin):
    cos, sin = cos[None, None], sin[None, None]
    return q * cos + rotate_half(q) * sin, k * cos + rotate_half(k) * sin


def repeat_kv(x, n_rep):
    if n_rep == 1:
        return x
    b, n_kv, t, hd = x.shape
    return x[:, :, None, :, :].expand(b, n_kv, n_rep, t, hd).reshape(b, n_kv * n_rep, t, hd)


class Attention(nn.Module):
    """Standard GQA used for the periodic full-attention layers in the hybrid stack."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.n_head, self.n_kv_head = cfg.n_head, cfg.n_kv_head
        self.n_rep = cfg.n_head // cfg.n_kv_head
        self.head_dim = cfg.head_dim
        self.q_proj = nn.Linear(cfg.n_embd, self.n_head * self.head_dim, bias=False)
        self.k_proj = nn.Linear(cfg.n_embd, self.n_kv_head * self.head_dim, bias=False)
        self.v_proj = nn.Linear(cfg.n_embd, self.n_kv_head * self.head_dim, bias=False)
        self.o_proj = nn.Linear(self.n_head * self.head_dim, cfg.n_embd, bias=False)

    def forward(self, x, cos, sin, mask):
        b, t, _ = x.shape
        q = self.q_proj(x).view(b, t, self.n_head, self.head_dim).transpose(1, 2)
        k = self.k_proj(x).view(b, t, self.n_kv_head, self.head_dim).transpose(1, 2)
        v = self.v_proj(x).view(b, t, self.n_kv_head, self.head_dim).transpose(1, 2)
        q, k = apply_rope(q, k, cos, sin)
        k, v = repeat_kv(k, self.n_rep), repeat_kv(v, self.n_rep)
        att = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)
        att = att.masked_fill(mask[:t, :t], float("-inf"))
        att = F.softmax(att, dim=-1)
        y = (att @ v).transpose(1, 2).reshape(b, t, self.n_head * self.head_dim)
        return self.o_proj(y)


# --------------------------------------------------------------------------------------------------
# Feed-forward (MoE or dense)
# --------------------------------------------------------------------------------------------------
class MLP(nn.Module):
    """SwiGLU expert MLP; used both as the dense fallback and as a single routed expert."""

    def __init__(self, n_embd, intermediate):
        super().__init__()
        self.gate_proj = nn.Linear(n_embd, intermediate, bias=False)
        self.up_proj = nn.Linear(n_embd, intermediate, bias=False)
        self.down_proj = nn.Linear(intermediate, n_embd, bias=False)

    def forward(self, x):
        return self.down_proj(F.silu(self.gate_proj(x)) * self.up_proj(x))


class MoE(nn.Module):
    """Sparse top-k MoE with optional always-on shared expert."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.n_experts, self.top_k = cfg.n_experts, cfg.n_experts_per_tok
        self.gate = nn.Linear(cfg.n_embd, cfg.n_experts, bias=False)
        self.experts = nn.ModuleList(MLP(cfg.n_embd, cfg.moe_intermediate_size) for _ in range(cfg.n_experts))
        self.shared = (
            MLP(cfg.n_embd, cfg.moe_intermediate_size * cfg.n_shared_experts)
            if cfg.n_shared_experts > 0 else None
        )

    def forward(self, x):
        b, t, c = x.shape
        x = x.reshape(-1, c)
        topw, topi = F.softmax(self.gate(x), dim=-1).topk(self.top_k, dim=-1)
        topw = topw / topw.sum(dim=-1, keepdim=True)
        out = torch.zeros_like(x)
        for e in range(self.n_experts):
            sel = topi == e
            if not sel.any():
                continue
            ti, slot = sel.nonzero(as_tuple=True)
            out[ti] += topw[ti, slot].unsqueeze(-1) * self.experts[e](x[ti])
        if self.shared is not None:
            out = out + self.shared(x)
        return out.reshape(b, t, c)


class MambaLayer(nn.Module):
    """Standalone ``M`` layer from the NemotronH macro pattern: norm + Mamba residual."""

    layer_type = "M"

    def __init__(self, cfg: Config):
        super().__init__()
        self.norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.mix = Mamba(cfg)

    def forward(self, x, cos, sin, mask):
        return x + self.mix(self.norm(x))


class AttentionLayer(nn.Module):
    """Standalone ``*`` layer from the NemotronH macro pattern: norm + GQA residual."""

    layer_type = "*"
    is_attn = True

    def __init__(self, cfg: Config):
        super().__init__()
        self.norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.attn = Attention(cfg)

    def forward(self, x, cos, sin, mask):
        return x + self.attn(self.norm(x), cos, sin, mask)


class FFNLayer(nn.Module):
    """Standalone ``E`` layer from the NemotronH macro pattern: norm + MoE/dense residual."""

    layer_type = "E"

    def __init__(self, cfg: Config):
        super().__init__()
        self.norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.ffn = MoE(cfg) if cfg.use_moe else MLP(cfg.n_embd, cfg.intermediate_size)

    def forward(self, x, cos, sin, mask):
        return x + self.ffn(self.norm(x))


# --------------------------------------------------------------------------------------------------
# Model
# --------------------------------------------------------------------------------------------------
class Model(nn.Module):
    """Full language model: embed tokens, run the NemotronH M/E/* layer pattern, project to logits."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.config = cfg
        self.tok_emb = nn.Embedding(cfg.vocab_size, cfg.n_embd)
        if len(cfg.layer_pattern) != cfg.n_layer:
            raise ValueError("cfg.layer_pattern length must equal cfg.n_layer")
        layer_types = {"M": MambaLayer, "E": FFNLayer, "*": AttentionLayer}
        self.blocks = nn.ModuleList(layer_types[c](cfg) for c in cfg.layer_pattern)
        self.norm = RMSNorm(cfg.n_embd, cfg.norm_eps)
        self.lm_head = nn.Linear(cfg.n_embd, cfg.vocab_size, bias=False)
        if cfg.tie_embeddings:
            self.lm_head.weight = self.tok_emb.weight
        cos, sin = precompute_rope(cfg.head_dim, cfg.context_length, cfg.rope_theta)
        self.register_buffer("rope_cos", cos, persistent=False)
        self.register_buffer("rope_sin", sin, persistent=False)
        causal = torch.triu(
            torch.ones(cfg.context_length, cfg.context_length, dtype=torch.bool), diagonal=1
        )
        self.register_buffer("causal_mask", causal, persistent=False)
        self.apply(self._init_weights)

    def _init_weights(self, m: nn.Module) -> None:
        if isinstance(m, nn.Linear):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, nn.Embedding):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)

    def forward(self, idx: torch.Tensor) -> torch.Tensor:
        b, t = idx.shape
        x = self.tok_emb(idx)
        cos, sin = self.rope_cos[:t], self.rope_sin[:t]
        for block in self.blocks:
            x = block(x, cos, sin, self.causal_mask)
        return self.lm_head(self.norm(x))


# --------------------------------------------------------------------------------------------------
# Standalone smoke test: `python llm_gallery/models/nemotron3_nano_30b.py`
# --------------------------------------------------------------------------------------------------
if __name__ == "__main__":
    torch.manual_seed(0)
    cfg = PRESETS["tiny"]
    model = Model(cfg)
    idx = torch.randint(0, cfg.vocab_size, (2, 16))
    logits = model(idx)
    loss = F.cross_entropy(logits.reshape(-1, logits.size(-1)), idx.reshape(-1))
    loss.backward()
    n_mamba = sum(b.layer_type == "M" for b in model.blocks)
    n_moe = sum(b.layer_type == "E" for b in model.blocks)
    n_attn = sum(b.layer_type == "*" for b in model.blocks)
    print(f"{MODEL_NAME}  (tiny preset)")
    print(f"  layers : {n_mamba} Mamba + {n_moe} MoE/FFN + {n_attn} attention")
    print(f"  params : {sum(p.numel() for p in model.parameters()):,}")
    print(f"  logits : {tuple(logits.shape)}  loss {loss.item():.4f}  (~ln(vocab)={math.log(cfg.vocab_size):.4f})")
